/* FORM — Datenbank: Lebensmittel, Übungen, Trainingspläne
   Alle Nährwerte pro 100g / 100ml. Alle Werte sind Richtwerte. */

const FOOD_DB = [
  // Getreide / Kohlenhydrate
  { id: 'haferflocken', name: 'Haferflocken', kcal: 372, protein: 13.5, carbs: 58, fat: 7 },
  { id: 'reis_roh', name: 'Reis (weiß, roh)', kcal: 350, protein: 7, carbs: 77, fat: 0.6 },
  { id: 'reis_gekocht', name: 'Reis (weiß, gekocht)', kcal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { id: 'vollkornreis_roh', name: 'Vollkornreis (roh)', kcal: 350, protein: 7.5, carbs: 72, fat: 2.8 },
  { id: 'nudeln_roh', name: 'Nudeln (roh)', kcal: 350, protein: 12, carbs: 70, fat: 1.5 },
  { id: 'nudeln_gekocht', name: 'Nudeln (gekocht)', kcal: 158, protein: 5.8, carbs: 30.9, fat: 0.9 },
  { id: 'vollkornnudeln_gekocht', name: 'Vollkornnudeln (gekocht)', kcal: 124, protein: 5, carbs: 25, fat: 0.9 },
  { id: 'kartoffeln', name: 'Kartoffeln', kcal: 77, protein: 2, carbs: 17, fat: 0.1 },
  { id: 'suesskartoffel', name: 'Süßkartoffel', kcal: 86, protein: 1.6, carbs: 20, fat: 0.1 },
  { id: 'brot_vollkorn', name: 'Brot (Vollkorn)', kcal: 219, protein: 9, carbs: 40, fat: 2 },
  { id: 'brot_weiss', name: 'Brot (Weißbrot)', kcal: 265, protein: 9, carbs: 49, fat: 2.5 },
  { id: 'toastbrot', name: 'Toastbrot', kcal: 250, protein: 8, carbs: 47, fat: 3 },
  { id: 'knaeckebrot', name: 'Knäckebrot', kcal: 350, protein: 10, carbs: 68, fat: 2 },
  { id: 'broetchen', name: 'Brötchen', kcal: 275, protein: 8.5, carbs: 55, fat: 1.5 },
  { id: 'reiswaffeln', name: 'Reiswaffeln', kcal: 387, protein: 8, carbs: 82, fat: 3 },
  { id: 'couscous_gekocht', name: 'Couscous (gekocht)', kcal: 112, protein: 3.8, carbs: 23, fat: 0.2 },
  { id: 'quinoa_gekocht', name: 'Quinoa (gekocht)', kcal: 120, protein: 4.4, carbs: 21, fat: 1.9 },
  { id: 'bulgur_gekocht', name: 'Bulgur (gekocht)', kcal: 83, protein: 3, carbs: 19, fat: 0.2 },
  { id: 'hirse_gekocht', name: 'Hirse (gekocht)', kcal: 119, protein: 3.5, carbs: 23, fat: 1.7 },
  { id: 'griess', name: 'Grieß', kcal: 356, protein: 12, carbs: 71, fat: 1.1 },
  { id: 'muesli', name: 'Müsli (ungesüßt)', kcal: 370, protein: 10, carbs: 62, fat: 8 },
  { id: 'cornflakes', name: 'Cornflakes', kcal: 378, protein: 7, carbs: 84, fat: 1 },

  // Milchprodukte
  { id: 'magerquark', name: 'Magerquark', kcal: 67, protein: 12, carbs: 4, fat: 0.2 },
  { id: 'quark_20', name: 'Quark (20%)', kcal: 111, protein: 12, carbs: 3.5, fat: 5.5 },
  { id: 'skyr', name: 'Skyr', kcal: 63, protein: 11, carbs: 4, fat: 0.2 },
  { id: 'joghurt_natur', name: 'Naturjoghurt (1,5%)', kcal: 63, protein: 4.5, carbs: 6, fat: 1.5 },
  { id: 'griech_joghurt', name: 'Griechischer Joghurt (10%)', kcal: 133, protein: 6, carbs: 4, fat: 10 },
  { id: 'milch_15', name: 'Milch (1,5%)', kcal: 47, protein: 3.4, carbs: 4.9, fat: 1.5 },
  { id: 'milch_35', name: 'Milch (3,5%)', kcal: 64, protein: 3.3, carbs: 4.8, fat: 3.6 },
  { id: 'buttermilch', name: 'Buttermilch', kcal: 34, protein: 3.4, carbs: 4.8, fat: 0.5 },
  { id: 'huettenkaese', name: 'Hüttenkäse', kcal: 98, protein: 12, carbs: 3, fat: 4.3 },
  { id: 'frischkaese', name: 'Frischkäse', kcal: 245, protein: 7, carbs: 4, fat: 23 },
  { id: 'mozzarella', name: 'Mozzarella', kcal: 280, protein: 22, carbs: 2, fat: 21 },
  { id: 'gouda', name: 'Gouda', kcal: 356, protein: 25, carbs: 0, fat: 28 },
  { id: 'feta', name: 'Feta', kcal: 264, protein: 14, carbs: 4, fat: 21 },
  { id: 'parmesan', name: 'Parmesan', kcal: 392, protein: 35, carbs: 4, fat: 26 },
  { id: 'butter', name: 'Butter', kcal: 717, protein: 0.6, carbs: 0.6, fat: 81 },

  // Eier, Fleisch, Fisch
  { id: 'ei', name: 'Ei (ganz)', kcal: 155, protein: 13, carbs: 1.1, fat: 11 },
  { id: 'eiweiss', name: 'Eiweiß', kcal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  { id: 'haehnchenbrust', name: 'Hähnchenbrust (roh)', kcal: 110, protein: 23, carbs: 0, fat: 1.2 },
  { id: 'haehnchenschenkel', name: 'Hähnchenschenkel', kcal: 180, protein: 18, carbs: 0, fat: 12 },
  { id: 'putenbrust', name: 'Putenbrust', kcal: 104, protein: 24, carbs: 0, fat: 1 },
  { id: 'rinderhack', name: 'Rinderhack (10%)', kcal: 215, protein: 18, carbs: 0, fat: 15 },
  { id: 'rinderfilet', name: 'Rinderfilet', kcal: 133, protein: 21, carbs: 0, fat: 5 },
  { id: 'schweinefilet', name: 'Schweinefilet', kcal: 143, protein: 21, carbs: 0, fat: 6 },
  { id: 'lachs', name: 'Lachs', kcal: 208, protein: 20, carbs: 0, fat: 13 },
  { id: 'thunfisch_dose', name: 'Thunfisch (Dose, im Wasser)', kcal: 116, protein: 26, carbs: 0, fat: 1 },
  { id: 'garnelen', name: 'Garnelen', kcal: 71, protein: 15, carbs: 0.9, fat: 0.6 },
  { id: 'kabeljau', name: 'Kabeljau', kcal: 82, protein: 18, carbs: 0, fat: 0.7 },
  { id: 'kochschinken', name: 'Kochschinken', kcal: 106, protein: 18, carbs: 1, fat: 3 },
  { id: 'salami', name: 'Salami', kcal: 425, protein: 22, carbs: 1, fat: 38 },
  { id: 'lachsschinken', name: 'Lachsschinken', kcal: 125, protein: 20, carbs: 0.5, fat: 4.5 },

  // Hülsenfrüchte / pflanzliches Protein
  { id: 'linsen_gekocht', name: 'Linsen (gekocht)', kcal: 116, protein: 9, carbs: 20, fat: 0.4 },
  { id: 'kichererbsen_gekocht', name: 'Kichererbsen (gekocht)', kcal: 164, protein: 8.9, carbs: 27, fat: 2.6 },
  { id: 'kidneybohnen_gekocht', name: 'Kidneybohnen (gekocht)', kcal: 127, protein: 8.7, carbs: 22, fat: 0.5 },
  { id: 'tofu', name: 'Tofu', kcal: 121, protein: 13, carbs: 2, fat: 7 },
  { id: 'edamame', name: 'Edamame', kcal: 122, protein: 11, carbs: 9, fat: 5 },
  { id: 'erbsen', name: 'Erbsen', kcal: 81, protein: 5.4, carbs: 14, fat: 0.4 },
  { id: 'hummus', name: 'Hummus', kcal: 166, protein: 7.9, carbs: 14, fat: 9.6 },

  // Nüsse, Samen, Fette
  { id: 'mandeln', name: 'Mandeln', kcal: 579, protein: 21, carbs: 22, fat: 50 },
  { id: 'walnuesse', name: 'Walnüsse', kcal: 654, protein: 15, carbs: 14, fat: 65 },
  { id: 'erdnuesse', name: 'Erdnüsse', kcal: 567, protein: 26, carbs: 16, fat: 49 },
  { id: 'erdnussbutter', name: 'Erdnussbutter', kcal: 588, protein: 25, carbs: 20, fat: 50 },
  { id: 'cashewkerne', name: 'Cashewkerne', kcal: 553, protein: 18, carbs: 30, fat: 44 },
  { id: 'chiasamen', name: 'Chiasamen', kcal: 486, protein: 17, carbs: 42, fat: 31 },
  { id: 'leinsamen', name: 'Leinsamen', kcal: 534, protein: 18, carbs: 29, fat: 42 },
  { id: 'olivenoel', name: 'Olivenöl', kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { id: 'rapsoel', name: 'Rapsöl', kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { id: 'kokosoel', name: 'Kokosöl', kcal: 862, protein: 0, carbs: 0, fat: 100 },
  { id: 'sonnenblumenkerne', name: 'Sonnenblumenkerne', kcal: 584, protein: 21, carbs: 20, fat: 51 },

  // Obst
  { id: 'banane', name: 'Banane', kcal: 89, protein: 1.1, carbs: 23, fat: 0.3 },
  { id: 'apfel', name: 'Apfel', kcal: 52, protein: 0.3, carbs: 14, fat: 0.2 },
  { id: 'birne', name: 'Birne', kcal: 57, protein: 0.4, carbs: 15, fat: 0.1 },
  { id: 'orange', name: 'Orange', kcal: 47, protein: 0.9, carbs: 12, fat: 0.1 },
  { id: 'erdbeeren', name: 'Erdbeeren', kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3 },
  { id: 'heidelbeeren', name: 'Heidelbeeren', kcal: 57, protein: 0.7, carbs: 14, fat: 0.3 },
  { id: 'himbeeren', name: 'Himbeeren', kcal: 52, protein: 1.2, carbs: 12, fat: 0.7 },
  { id: 'weintrauben', name: 'Weintrauben', kcal: 69, protein: 0.6, carbs: 18, fat: 0.2 },
  { id: 'ananas', name: 'Ananas', kcal: 50, protein: 0.5, carbs: 13, fat: 0.1 },
  { id: 'mango', name: 'Mango', kcal: 60, protein: 0.8, carbs: 15, fat: 0.4 },
  { id: 'kiwi', name: 'Kiwi', kcal: 61, protein: 1.1, carbs: 15, fat: 0.5 },
  { id: 'wassermelone', name: 'Wassermelone', kcal: 30, protein: 0.6, carbs: 8, fat: 0.2 },
  { id: 'zitrone', name: 'Zitrone', kcal: 29, protein: 1.1, carbs: 9, fat: 0.3 },
  { id: 'avocado', name: 'Avocado', kcal: 160, protein: 2, carbs: 8.5, fat: 15 },
  { id: 'pfirsich', name: 'Pfirsich', kcal: 39, protein: 0.9, carbs: 10, fat: 0.3 },
  { id: 'datteln', name: 'Datteln (getrocknet)', kcal: 277, protein: 2, carbs: 75, fat: 0.4 },
  { id: 'rosinen', name: 'Rosinen', kcal: 299, protein: 3.1, carbs: 79, fat: 0.5 },

  // Gemüse
  { id: 'brokkoli', name: 'Brokkoli', kcal: 34, protein: 2.8, carbs: 7, fat: 0.4 },
  { id: 'blumenkohl', name: 'Blumenkohl', kcal: 25, protein: 1.9, carbs: 5, fat: 0.3 },
  { id: 'spinat', name: 'Spinat', kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { id: 'gruenkohl', name: 'Grünkohl', kcal: 49, protein: 4.3, carbs: 9, fat: 0.9 },
  { id: 'tomate', name: 'Tomate', kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { id: 'gurke', name: 'Gurke', kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
  { id: 'paprika', name: 'Paprika', kcal: 31, protein: 1, carbs: 6, fat: 0.3 },
  { id: 'karotte', name: 'Karotte', kcal: 41, protein: 0.9, carbs: 10, fat: 0.2 },
  { id: 'zucchini', name: 'Zucchini', kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  { id: 'aubergine', name: 'Aubergine', kcal: 25, protein: 1, carbs: 6, fat: 0.2 },
  { id: 'zwiebel', name: 'Zwiebel', kcal: 40, protein: 1.1, carbs: 9, fat: 0.1 },
  { id: 'knoblauch', name: 'Knoblauch', kcal: 149, protein: 6.4, carbs: 33, fat: 0.5 },
  { id: 'champignons', name: 'Champignons', kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  { id: 'rote_bete', name: 'Rote Bete', kcal: 43, protein: 1.6, carbs: 10, fat: 0.2 },
  { id: 'feldsalat', name: 'Feldsalat', kcal: 20, protein: 2, carbs: 1.6, fat: 0.4 },
  { id: 'rucola', name: 'Rucola', kcal: 25, protein: 2.6, carbs: 2, fat: 0.7 },
  { id: 'eisbergsalat', name: 'Eisbergsalat', kcal: 14, protein: 0.9, carbs: 2.1, fat: 0.2 },
  { id: 'suessmais', name: 'Süßmais', kcal: 86, protein: 3.2, carbs: 19, fat: 1.2 },

  // Sonstiges, Snacks, Getränke
  { id: 'honig', name: 'Honig', kcal: 304, protein: 0.3, carbs: 82, fat: 0 },
  { id: 'ahornsirup', name: 'Ahornsirup', kcal: 260, protein: 0, carbs: 67, fat: 0.2 },
  { id: 'zucker', name: 'Zucker', kcal: 400, protein: 0, carbs: 100, fat: 0 },
  { id: 'schokolade_70', name: 'Dunkle Schokolade (70%)', kcal: 598, protein: 7.8, carbs: 45, fat: 42 },
  { id: 'vollmilchschokolade', name: 'Vollmilchschokolade', kcal: 534, protein: 7.6, carbs: 57, fat: 30 },
  { id: 'proteinpulver', name: 'Proteinpulver (Whey)', kcal: 380, protein: 75, carbs: 8, fat: 6 },
  { id: 'haferdrink', name: 'Haferdrink', kcal: 47, protein: 1, carbs: 6.5, fat: 1.5 },
  { id: 'mandeldrink', name: 'Mandeldrink', kcal: 24, protein: 0.4, carbs: 2.5, fat: 1.1 },
  { id: 'sojamilch', name: 'Sojamilch', kcal: 33, protein: 3.3, carbs: 1.5, fat: 1.8 },
  { id: 'apfelsaft', name: 'Apfelsaft', kcal: 46, protein: 0.1, carbs: 11, fat: 0.1 },
  { id: 'orangensaft', name: 'Orangensaft', kcal: 45, protein: 0.7, carbs: 10, fat: 0.2 },
  { id: 'cola', name: 'Cola', kcal: 42, protein: 0, carbs: 10.6, fat: 0 },
  { id: 'bier', name: 'Bier', kcal: 43, protein: 0.5, carbs: 3.5, fat: 0 },
  { id: 'rotwein', name: 'Rotwein', kcal: 85, protein: 0.1, carbs: 2.6, fat: 0 },
  { id: 'pommes', name: 'Pommes frites', kcal: 312, protein: 3.4, carbs: 41, fat: 15 },
  { id: 'pizza_margherita', name: 'Pizza Margherita', kcal: 266, protein: 11, carbs: 33, fat: 10 },
  { id: 'doener', name: 'Döner Kebab', kcal: 220, protein: 15, carbs: 18, fat: 10 },
  { id: 'currywurst', name: 'Currywurst', kcal: 250, protein: 11, carbs: 10, fat: 18 },
  { id: 'nutella', name: 'Nutella', kcal: 539, protein: 6.3, carbs: 57, fat: 31 },
  { id: 'ketchup', name: 'Ketchup', kcal: 100, protein: 1.2, carbs: 24, fat: 0.2 },
  { id: 'senf', name: 'Senf', kcal: 76, protein: 4.4, carbs: 7.6, fat: 3.9 },
  { id: 'sojasauce', name: 'Sojasauce', kcal: 60, protein: 6, carbs: 6, fat: 0 },
  { id: 'essig', name: 'Essig', kcal: 21, protein: 0, carbs: 0.4, fat: 0 },
];

/* Übungen: Home-Training ohne Geräte (Körpergewicht + optional Kurzhanteln/Band) */
const EXERCISES = [
  // Brust
  { id: 'liegestuetze', name: 'Liegestütze', group: 'Brust', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Hände schulterbreit auf dem Boden, Körper bildet eine gerade Linie von Kopf bis Ferse. Brust kontrolliert Richtung Boden senken, dann kraftvoll nach oben drücken.' },
  { id: 'knie_liegestuetze', name: 'Knie-Liegestütze', group: 'Brust', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Wie Liegestütze, aber auf den Knien statt auf den Zehen abgestützt. Reduziert das Gewicht und ist ideal für den Einstieg.' },
  { id: 'diamant_liegestuetze', name: 'Diamant-Liegestütze', group: 'Brust', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Hände bilden unter der Brust eine Raute (Daumen und Zeigefinger berühren sich). Betont besonders Trizeps und inneren Brustmuskel.' },
  { id: 'schraege_liegestuetze', name: 'Schräge Liegestütze (Beine erhöht)', group: 'Brust', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Füße auf einer erhöhten Fläche wie einer Stufe oder einem Stuhl ablegen. Verlagert den Fokus auf die obere Brust.' },
  { id: 'enge_liegestuetze', name: 'Enge Liegestütze', group: 'Brust', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Hände enger als schulterbreit positionieren, Ellbogen eng am Körper führen. Fordert Trizeps und Brust gleichermaßen.' },
  { id: 'plyo_liegestuetze', name: 'Liegestütze mit Klatschen', group: 'Brust', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Explosiv aus der Liegestütz-Position abdrücken, in der Luft in die Hände klatschen und kontrolliert landen. Baut Kraft und Power auf.' },
  { id: 'brustpresse_kurzhantel', name: 'Brustpresse mit Kurzhanteln', group: 'Brust', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Rückenlage, Kurzhanteln über der Brust nach oben drücken, Ellbogen kontrolliert absenken. Gleichmäßige, ruhige Bewegung.' },
  { id: 'fliegende_kurzhantel', name: 'Fliegende mit Kurzhanteln', group: 'Brust', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Rückenlage, Arme mit leicht gebeugten Ellbogen seitlich absenken und wieder über der Brust zusammenführen. Dehnt und trainiert die Brustmuskulatur.' },

  // Rücken
  { id: 'superman', name: 'Superman', group: 'Rücken', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Bauchlage, Arme und Beine gleichzeitig vom Boden abheben und kurz halten. Stärkt die untere Rückenmuskulatur.' },
  { id: 'rueckenstrecker', name: 'Rückenstrecker (Boden)', group: 'Rücken', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Bauchlage, Hände hinter dem Kopf, Oberkörper langsam anheben und wieder absenken. Kontrolliert ausführen, kein Schwung.' },
  { id: 'reverse_snow_angels', name: 'Reverse Snow Angels', group: 'Rücken', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Bauchlage, Arme wie beim Schneeengel von den Seiten über den Kopf führen und zurück. Aktiviert die obere Rückenmuskulatur.' },
  { id: 'rudern_einarmig', name: 'Kurzhantel Rudern einarmig', group: 'Rücken', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Eine Hand und ein Knie auf einer Bank abstützen, Kurzhantel mit der anderen Hand zur Hüfte ziehen. Rücken gerade halten.' },
  { id: 'band_rudern', name: 'Widerstandsband Rudern', group: 'Rücken', level: 'Mittel', equipment: 'Widerstandsband',
    desc: 'Band um einen festen Punkt spannen, im Sitzen oder Stehen zur Körpermitte ziehen und Schulterblätter zusammenziehen.' },
  { id: 'klimmzuege', name: 'Klimmzüge', group: 'Rücken', level: 'Fortgeschritten', equipment: 'Klimmzugstange',
    desc: 'An einer Stange im Obergriff hängen, Körper hochziehen bis das Kinn über der Stange ist, kontrolliert absenken.' },
  { id: 'good_mornings', name: 'Good Mornings mit Kurzhanteln', group: 'Rücken', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Kurzhantel auf den Schultern, mit leicht gebeugten Knien den Oberkörper nach vorne beugen und wieder aufrichten. Rücken bleibt gerade.' },
  { id: 'band_pull_apart', name: 'Band Pull-Apart', group: 'Rücken', level: 'Anfänger', equipment: 'Widerstandsband',
    desc: 'Band mit ausgestreckten Armen vor der Brust halten und auseinanderziehen, bis es die Brust berührt. Schulterblätter aktiv zusammenziehen.' },

  // Beine
  { id: 'kniebeugen', name: 'Kniebeugen', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Füße schulterbreit, Hüfte nach hinten unten absenken als würde man sich auf einen Stuhl setzen, Knie bleiben über den Füßen.' },
  { id: 'ausfallschritte', name: 'Ausfallschritte', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Großer Schritt nach vorne, hinteres Knie Richtung Boden senken, beide Knie etwa 90 Grad. Zurück zur Ausgangsposition und Seite wechseln.' },
  { id: 'bulgarian_split_squat', name: 'Bulgarian Split Squats', group: 'Beine', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Hinterer Fuß erhöht auf einer Bank abgelegt, mit dem vorderen Bein in die Knie gehen. Fordert Kraft und Balance intensiv.' },
  { id: 'wall_sit', name: 'Wall Sit', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Rücken an eine Wand lehnen und in eine sitzende Position gehen, Oberschenkel parallel zum Boden. Position so lange wie möglich halten.' },
  { id: 'sumo_kniebeuge', name: 'Sumo-Kniebeugen', group: 'Beine', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Breiter Stand, Zehen leicht nach außen gedreht, tief in die Hocke gehen. Betont besonders die Innenschenkel und den Po.' },
  { id: 'jump_squats', name: 'Jump Squats', group: 'Beine', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Aus der Kniebeuge explosiv nach oben springen, weich landen und direkt in die nächste Wiederholung übergehen.' },
  { id: 'glute_bridge', name: 'Glute Bridge', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Rückenlage, Füße aufgestellt, Hüfte nach oben drücken bis der Körper eine gerade Linie bildet, oben kurz halten.' },
  { id: 'wadenheben', name: 'Wadenheben', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Im Stehen auf die Zehenspitzen heben und langsam wieder absenken. Für mehr Intensität auf einer Stufenkante ausführen.' },
  { id: 'kurzhantel_kniebeuge', name: 'Kurzhantel Kniebeuge', group: 'Beine', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Kurzhanteln seitlich am Körper halten und eine klassische Kniebeuge ausführen. Erhöht die Belastung gegenüber der Bodyweight-Variante.' },
  { id: 'step_ups', name: 'Step-Ups', group: 'Beine', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Auf eine stabile erhöhte Fläche wie eine Treppenstufe steigen, oben durchstrecken und kontrolliert zurück nach unten.' },

  // Schultern
  { id: 'pike_pushups', name: 'Pike Push-Ups', group: 'Schultern', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Hüfte hoch in eine umgekehrte V-Position bringen, Kopf Richtung Boden absenken und wieder hochdrücken. Betont die vordere Schulter.' },
  { id: 'schulterdruecken', name: 'Schulterdrücken mit Kurzhanteln', group: 'Schultern', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Im Stehen oder Sitzen Kurzhanteln von Schulterhöhe gerade nach oben drücken, ohne den unteren Rücken durchzudrücken.' },
  { id: 'seitheben', name: 'Seitheben mit Kurzhanteln', group: 'Schultern', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Kurzhanteln seitlich am Körper, Arme mit leicht gebeugten Ellbogen bis Schulterhöhe seitlich anheben, kontrolliert absenken.' },
  { id: 'frontheben', name: 'Frontheben mit Kurzhanteln', group: 'Schultern', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Kurzhanteln vor dem Körper, Arme nacheinander oder gemeinsam bis Schulterhöhe nach vorne anheben, langsam zurückführen.' },
  { id: 'arm_circles', name: 'Arm Circles', group: 'Schultern', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Arme seitlich ausstrecken und kleine, kontrollierte Kreise in beide Richtungen ausführen. Gutes Aufwärm- und Aktivierungsmittel.' },
  { id: 'handstand_pushup', name: 'Handstand Push-Up (Wand)', group: 'Schultern', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Im Handstand an der Wand die Arme beugen bis der Kopf sich dem Boden nähert und wieder hochdrücken. Nur mit guter Grundkraft ausführen.' },

  // Arme
  { id: 'bizeps_curls', name: 'Bizeps Curls mit Kurzhanteln', group: 'Arme', level: 'Anfänger', equipment: 'Kurzhanteln',
    desc: 'Oberarme fixiert am Körper, Kurzhanteln durch Beugen der Ellbogen zu den Schultern führen, langsam wieder absenken.' },
  { id: 'trizeps_dips', name: 'Trizeps Dips (Stuhl)', group: 'Arme', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Hände auf die Kante eines Stuhls oder einer Bank stützen, Körper absenken bis die Ellbogen ca. 90 Grad erreichen, wieder hochdrücken.' },
  { id: 'trizeps_kickback', name: 'Trizeps Kickback mit Kurzhantel', group: 'Arme', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Oberkörper leicht vorgebeugt, Oberarm parallel zum Boden, Unterarm nach hinten strecken bis der Arm ganz durchgestreckt ist.' },
  { id: 'hammer_curls', name: 'Hammer Curls', group: 'Arme', level: 'Anfänger', equipment: 'Kurzhanteln',
    desc: 'Kurzhanteln im neutralen Griff (Daumen zeigt nach oben) zu den Schultern curlen. Beansprucht zusätzlich den Unterarm.' },
  { id: 'unterarmrotation', name: 'Unterarmrotation mit Kurzhantel', group: 'Arme', level: 'Anfänger', equipment: 'Kurzhanteln',
    desc: 'Unterarm auf einem Oberschenkel abstützen, Handgelenk mit leichter Kurzhantel kontrolliert drehen. Stärkt Unterarm und Griffkraft.' },

  // Core
  { id: 'plank', name: 'Plank (Unterarmstütz)', group: 'Core', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Unterarme und Zehen am Boden, Körper bildet eine gerade Linie. Bauch und Gesäß aktiv anspannen, Position halten.' },
  { id: 'seitplank', name: 'Seitplank', group: 'Core', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Seitliche Stützposition auf einem Unterarm, Körper bildet eine gerade Linie von Kopf bis Fuß. Hüfte nicht absinken lassen.' },
  { id: 'crunches', name: 'Crunches', group: 'Core', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Rückenlage, Knie angewinkelt, Oberkörper kontrolliert Richtung Knie anheben und wieder absenken, ohne den Nacken zu belasten.' },
  { id: 'bicycle_crunches', name: 'Bicycle Crunches', group: 'Core', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Rückenlage, Ellbogen abwechselnd zum gegenüberliegenden Knie führen, während die Beine eine Radfahrbewegung ausführen.' },
  { id: 'mountain_climbers', name: 'Mountain Climbers', group: 'Core', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Aus der Liegestützposition die Knie abwechselnd schnell Richtung Brust ziehen. Trainiert Core und Herz-Kreislauf-System.' },
  { id: 'russian_twists', name: 'Russian Twists', group: 'Core', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Sitzposition mit leicht angehobenen Füßen, Oberkörper von einer Seite zur anderen drehen. Für mehr Intensität ein Gewicht mitführen.' },
  { id: 'beinheben', name: 'Beinheben', group: 'Core', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Rückenlage, gestreckte Beine kontrolliert anheben bis 90 Grad und langsam wieder absenken, unterer Rücken bleibt am Boden.' },
  { id: 'hollow_body_hold', name: 'Hollow Body Hold', group: 'Core', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Rückenlage, Arme und Beine gestreckt leicht vom Boden abheben, unterer Rücken bleibt gepresst. Position möglichst lange halten.' },
  { id: 'plank_updown', name: 'Plank Up-Down', group: 'Core', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Aus dem Unterarmstütz abwechselnd in den hohen Stütz auf die Hände hochdrücken und zurück, Hüfte bleibt dabei stabil.' },

  // Cardio
  { id: 'jumping_jacks', name: 'Jumping Jacks', group: 'Cardio', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Aus dem Stand gleichzeitig mit Armen und Beinen nach außen springen, dann zurück in die Ausgangsposition. Klassisches Cardio-Warm-up.' },
  { id: 'burpees', name: 'Burpees', group: 'Cardio', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'In die Hocke gehen, in die Liegestützposition springen, eine Liegestütz ausführen, zurückspringen und explosiv nach oben springen.' },
  { id: 'high_knees', name: 'High Knees', group: 'Cardio', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Auf der Stelle laufen und die Knie dabei so hoch wie möglich zur Brust ziehen. Zügiges Tempo für maximale Herzfrequenz.' },
  { id: 'seilspringen', name: 'Seilspringen', group: 'Cardio', level: 'Mittel', equipment: 'Springseil',
    desc: 'Gleichmäßiges Springen über das Seil mit lockeren Handgelenken. Effektives Ganzkörper-Cardio-Training.' },
  { id: 'skaters', name: 'Skaters', group: 'Cardio', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Seitliche Sprünge von einem Bein auf das andere, ähnlich einer Schlittschuh-Bewegung. Trainiert Beine und Koordination.' },
  { id: 'fast_mountain_climbers', name: 'Bergsteiger schnell', group: 'Cardio', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Mountain Climbers in schnellem, durchgehendem Tempo für einen erhöhten Cardio-Reiz statt reiner Core-Betonung.' },
  { id: 'shadow_boxing', name: 'Shadow Boxing', group: 'Cardio', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Lockeres Boxen gegen die Luft mit fließenden Schritten. Gelenkschonendes Cardio-Training, das sich beliebig steigern lässt.' },
];

const MUSCLE_GROUPS = ['Brust', 'Rücken', 'Beine', 'Schultern', 'Arme', 'Core', 'Cardio'];

/* Fertige Trainingspläne */
const WORKOUT_PLANS = [
  {
    id: 'starter',
    name: 'STARTER',
    subtitle: 'Ganzkörper für Einsteiger',
    level: 'Anfänger',
    daysPerWeek: 3,
    days: [
      { day: 'Tag 1', label: 'Ganzkörper A', exercises: [
        { exerciseId: 'kniebeugen', sets: 3, reps: '12' },
        { exerciseId: 'knie_liegestuetze', sets: 3, reps: '10' },
        { exerciseId: 'glute_bridge', sets: 3, reps: '15' },
        { exerciseId: 'band_rudern', sets: 3, reps: '12' },
        { exerciseId: 'plank', sets: 3, reps: '30s' },
      ]},
      { day: 'Tag 2', label: 'Ganzkörper B', exercises: [
        { exerciseId: 'ausfallschritte', sets: 3, reps: '10' },
        { exerciseId: 'superman', sets: 3, reps: '15' },
        { exerciseId: 'wall_sit', sets: 3, reps: '30s' },
        { exerciseId: 'band_pull_apart', sets: 3, reps: '15' },
        { exerciseId: 'crunches', sets: 3, reps: '15' },
      ]},
      { day: 'Tag 3', label: 'Ganzkörper C', exercises: [
        { exerciseId: 'sumo_kniebeuge', sets: 3, reps: '12' },
        { exerciseId: 'knie_liegestuetze', sets: 3, reps: '12' },
        { exerciseId: 'rueckenstrecker', sets: 3, reps: '12' },
        { exerciseId: 'wadenheben', sets: 3, reps: '20' },
        { exerciseId: 'seitplank', sets: 3, reps: '20s' },
      ]},
    ],
  },
  {
    id: 'split',
    name: 'SPLIT',
    subtitle: 'Ober-/Unterkörper, 4x pro Woche',
    level: 'Mittel',
    daysPerWeek: 4,
    days: [
      { day: 'Tag 1', label: 'Oberkörper A', exercises: [
        { exerciseId: 'liegestuetze', sets: 4, reps: '10-12' },
        { exerciseId: 'rudern_einarmig', sets: 4, reps: '12' },
        { exerciseId: 'schulterdruecken', sets: 3, reps: '12' },
        { exerciseId: 'bizeps_curls', sets: 3, reps: '12' },
        { exerciseId: 'trizeps_dips', sets: 3, reps: '12' },
      ]},
      { day: 'Tag 2', label: 'Unterkörper A', exercises: [
        { exerciseId: 'kurzhantel_kniebeuge', sets: 4, reps: '10-12' },
        { exerciseId: 'ausfallschritte', sets: 3, reps: '12' },
        { exerciseId: 'glute_bridge', sets: 3, reps: '15' },
        { exerciseId: 'wadenheben', sets: 4, reps: '20' },
        { exerciseId: 'plank', sets: 3, reps: '45s' },
      ]},
      { day: 'Tag 3', label: 'Oberkörper B', exercises: [
        { exerciseId: 'schraege_liegestuetze', sets: 4, reps: '10-12' },
        { exerciseId: 'band_rudern', sets: 4, reps: '12' },
        { exerciseId: 'seitheben', sets: 3, reps: '15' },
        { exerciseId: 'hammer_curls', sets: 3, reps: '12' },
        { exerciseId: 'trizeps_kickback', sets: 3, reps: '12' },
      ]},
      { day: 'Tag 4', label: 'Unterkörper B', exercises: [
        { exerciseId: 'bulgarian_split_squat', sets: 3, reps: '10' },
        { exerciseId: 'sumo_kniebeuge', sets: 4, reps: '12' },
        { exerciseId: 'step_ups', sets: 3, reps: '12' },
        { exerciseId: 'russian_twists', sets: 3, reps: '20' },
        { exerciseId: 'seitplank', sets: 3, reps: '30s' },
      ]},
    ],
  },
  {
    id: 'hiit_home',
    name: 'HIIT HOME',
    subtitle: 'Cardio & Core, 20 Minuten',
    level: 'Mittel',
    daysPerWeek: 3,
    days: [
      { day: 'Tag 1', label: 'HIIT A', exercises: [
        { exerciseId: 'jumping_jacks', sets: 4, reps: '40s' },
        { exerciseId: 'mountain_climbers', sets: 4, reps: '40s' },
        { exerciseId: 'high_knees', sets: 4, reps: '40s' },
        { exerciseId: 'plank', sets: 4, reps: '40s' },
      ]},
      { day: 'Tag 2', label: 'HIIT B', exercises: [
        { exerciseId: 'burpees', sets: 4, reps: '30s' },
        { exerciseId: 'skaters', sets: 4, reps: '40s' },
        { exerciseId: 'bicycle_crunches', sets: 4, reps: '40s' },
        { exerciseId: 'plank_updown', sets: 4, reps: '30s' },
      ]},
      { day: 'Tag 3', label: 'HIIT C', exercises: [
        { exerciseId: 'fast_mountain_climbers', sets: 4, reps: '40s' },
        { exerciseId: 'jump_squats', sets: 4, reps: '30s' },
        { exerciseId: 'russian_twists', sets: 4, reps: '40s' },
        { exerciseId: 'hollow_body_hold', sets: 4, reps: '20s' },
      ]},
    ],
  },
  {
    id: 'ppl',
    name: 'PUSH PULL LEGS',
    subtitle: 'Fortgeschritten, 6x pro Woche',
    level: 'Fortgeschritten',
    daysPerWeek: 6,
    days: [
      { day: 'Tag 1', label: 'Push A', exercises: [
        { exerciseId: 'liegestuetze', sets: 4, reps: '10-15' },
        { exerciseId: 'diamant_liegestuetze', sets: 3, reps: '10' },
        { exerciseId: 'schulterdruecken', sets: 4, reps: '10-12' },
        { exerciseId: 'seitheben', sets: 3, reps: '15' },
        { exerciseId: 'trizeps_dips', sets: 3, reps: '12-15' },
      ]},
      { day: 'Tag 2', label: 'Pull A', exercises: [
        { exerciseId: 'klimmzuege', sets: 4, reps: '6-10' },
        { exerciseId: 'rudern_einarmig', sets: 4, reps: '10-12' },
        { exerciseId: 'good_mornings', sets: 3, reps: '12' },
        { exerciseId: 'bizeps_curls', sets: 3, reps: '12' },
        { exerciseId: 'hammer_curls', sets: 3, reps: '12' },
      ]},
      { day: 'Tag 3', label: 'Legs A', exercises: [
        { exerciseId: 'kurzhantel_kniebeuge', sets: 4, reps: '10-12' },
        { exerciseId: 'bulgarian_split_squat', sets: 3, reps: '10' },
        { exerciseId: 'glute_bridge', sets: 4, reps: '15' },
        { exerciseId: 'wadenheben', sets: 4, reps: '20' },
        { exerciseId: 'plank', sets: 3, reps: '45s' },
      ]},
      { day: 'Tag 4', label: 'Push B', exercises: [
        { exerciseId: 'schraege_liegestuetze', sets: 4, reps: '10-15' },
        { exerciseId: 'pike_pushups', sets: 3, reps: '8-10' },
        { exerciseId: 'fliegende_kurzhantel', sets: 3, reps: '12' },
        { exerciseId: 'frontheben', sets: 3, reps: '15' },
        { exerciseId: 'trizeps_kickback', sets: 3, reps: '12' },
      ]},
      { day: 'Tag 5', label: 'Pull B', exercises: [
        { exerciseId: 'band_rudern', sets: 4, reps: '12-15' },
        { exerciseId: 'reverse_snow_angels', sets: 3, reps: '15' },
        { exerciseId: 'band_pull_apart', sets: 3, reps: '20' },
        { exerciseId: 'unterarmrotation', sets: 3, reps: '15' },
        { exerciseId: 'plank_updown', sets: 3, reps: '30s' },
      ]},
      { day: 'Tag 6', label: 'Legs B', exercises: [
        { exerciseId: 'sumo_kniebeuge', sets: 4, reps: '12-15' },
        { exerciseId: 'ausfallschritte', sets: 3, reps: '12' },
        { exerciseId: 'step_ups', sets: 3, reps: '12' },
        { exerciseId: 'jump_squats', sets: 3, reps: '15' },
        { exerciseId: 'russian_twists', sets: 3, reps: '20' },
      ]},
    ],
  },
];

if (typeof module !== 'undefined') {
  module.exports = { FOOD_DB, EXERCISES, MUSCLE_GROUPS, WORKOUT_PLANS };
}
