/* FORM — Datenbank: Lebensmittel, Übungen, Trainingspläne
   Alle Nährwerte pro 100g / 100ml. Alle Werte sind Richtwerte. */

const FOOD_DB = [
  // Getreide / Kohlenhydrate
  { id: 'haferflocken', name: 'Haferflocken', kcal: 372, protein: 13.5, carbs: 58, fat: 7 },
  { id: 'reis_roh', name: 'Reis (weiß, roh)', kcal: 350, protein: 7, carbs: 77, fat: 0.6 },
  { id: 'reis_gekocht', name: 'Reis (weiß, gekocht)', kcal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { id: 'vollkornreis_roh', name: 'Vollkornreis (roh)', kcal: 350, protein: 7.5, carbs: 72, fat: 2.8 },
  { id: 'nudeln_roh', name: 'Nudeln (roh)', kcal: 350, protein: 12, carbs: 70, fat: 1.5 },
  { id: 'nudeln_gekocht', name: 'Nudeln (gekocht)', kcal: 158, protein: 5.8, carbs: 30.9, fat: 0.9 },
  { id: 'vollkornnudeln_gekocht', name: 'Vollkornnudeln (gekocht)', kcal: 124, protein: 5, carbs: 25, fat: 0.9 },
  { id: 'kartoffeln', name: 'Kartoffeln', kcal: 77, protein: 2, carbs: 17, fat: 0.1 },
  { id: 'suesskartoffel', name: 'Süßkartoffel', kcal: 86, protein: 1.6, carbs: 20, fat: 0.1 },
  { id: 'brot_vollkorn', name: 'Brot (Vollkorn)', kcal: 219, protein: 9, carbs: 40, fat: 2 },
  { id: 'brot_weiss', name: 'Brot (Weißbrot)', kcal: 265, protein: 9, carbs: 49, fat: 2.5 },
  { id: 'toastbrot', name: 'Toastbrot', kcal: 250, protein: 8, carbs: 47, fat: 3 },
  { id: 'knaeckebrot', name: 'Knäckebrot', kcal: 350, protein: 10, carbs: 68, fat: 2 },
  { id: 'broetchen', name: 'Brötchen', kcal: 275, protein: 8.5, carbs: 55, fat: 1.5 },
  { id: 'reiswaffeln', name: 'Reiswaffeln', kcal: 387, protein: 8, carbs: 82, fat: 3 },
  { id: 'couscous_gekocht', name: 'Couscous (gekocht)', kcal: 112, protein: 3.8, carbs: 23, fat: 0.2 },
  { id: 'quinoa_gekocht', name: 'Quinoa (gekocht)', kcal: 120, protein: 4.4, carbs: 21, fat: 1.9 },
  { id: 'bulgur_gekocht', name: 'Bulgur (gekocht)', kcal: 83, protein: 3, carbs: 19, fat: 0.2 },
  { id: 'hirse_gekocht', name: 'Hirse (gekocht)', kcal: 119, protein: 3.5, carbs: 23, fat: 1.7 },
  { id: 'griess', name: 'Grieß', kcal: 356, protein: 12, carbs: 71, fat: 1.1 },
  { id: 'muesli', name: 'Müsli (ungesüßt)', kcal: 370, protein: 10, carbs: 62, fat: 8 },
  { id: 'cornflakes', name: 'Cornflakes', kcal: 378, protein: 7, carbs: 84, fat: 1 },

  // Milchprodukte
  { id: 'magerquark', name: 'Magerquark', kcal: 67, protein: 12, carbs: 4, fat: 0.2 },
  { id: 'quark_20', name: 'Quark (20%)', kcal: 111, protein: 12, carbs: 3.5, fat: 5.5 },
  { id: 'skyr', name: 'Skyr', kcal: 63, protein: 11, carbs: 4, fat: 0.2 },
  { id: 'joghurt_natur', name: 'Naturjoghurt (1,5%)', kcal: 63, protein: 4.5, carbs: 6, fat: 1.5 },
  { id: 'griech_joghurt', name: 'Griechischer Joghurt (10%)', kcal: 133, protein: 6, carbs: 4, fat: 10 },
  { id: 'milch_15', name: 'Milch (1,5%)', kcal: 47, protein: 3.4, carbs: 4.9, fat: 1.5 },
  { id: 'milch_35', name: 'Milch (3,5%)', kcal: 64, protein: 3.3, carbs: 4.8, fat: 3.6 },
  { id: 'buttermilch', name: 'Buttermilch', kcal: 34, protein: 3.4, carbs: 4.8, fat: 0.5 },
  { id: 'huettenkaese', name: 'Hüttenkäse', kcal: 98, protein: 12, carbs: 3, fat: 4.3 },
  { id: 'frischkaese', name: 'Frischkäse', kcal: 245, protein: 7, carbs: 4, fat: 23 },
  { id: 'mozzarella', name: 'Mozzarella', kcal: 280, protein: 22, carbs: 2, fat: 21 },
  { id: 'gouda', name: 'Gouda', kcal: 356, protein: 25, carbs: 0, fat: 28 },
  { id: 'feta', name: 'Feta', kcal: 264, protein: 14, carbs: 4, fat: 21 },
  { id: 'parmesan', name: 'Parmesan', kcal: 392, protein: 35, carbs: 4, fat: 26 },
  { id: 'butter', name: 'Butter', kcal: 717, protein: 0.6, carbs: 0.6, fat: 81 },

  // Eier, Fleisch, Fisch
  { id: 'ei', name: 'Ei (ganz)', kcal: 155, protein: 13, carbs: 1.1, fat: 11 },
  { id: 'eiweiss', name: 'Eiweiß', kcal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  { id: 'haehnchenbrust', name: 'Hähnchenbrust (roh)', kcal: 110, protein: 23, carbs: 0, fat: 1.2 },
  { id: 'haehnchenschenkel', name: 'Hähnchenschenkel', kcal: 180, protein: 18, carbs: 0, fat: 12 },
  { id: 'putenbrust', name: 'Putenbrust', kcal: 104, protein: 24, carbs: 0, fat: 1 },
  { id: 'rinderhack', name: 'Rinderhack (10%)', kcal: 215, protein: 18, carbs: 0, fat: 15 },
  { id: 'rinderfilet', name: 'Rinderfilet', kcal: 133, protein: 21, carbs: 0, fat: 5 },
  { id: 'schweinefilet', name: 'Schweinefilet', kcal: 143, protein: 21, carbs: 0, fat: 6 },
  { id: 'lachs', name: 'Lachs', kcal: 208, protein: 20, carbs: 0, fat: 13 },
  { id: 'thunfisch_dose', name: 'Thunfisch (Dose, im Wasser)', kcal: 116, protein: 26, carbs: 0, fat: 1 },
  { id: 'garnelen', name: 'Garnelen', kcal: 71, protein: 15, carbs: 0.9, fat: 0.6 },
  { id: 'kabeljau', name: 'Kabeljau', kcal: 82, protein: 18, carbs: 0, fat: 0.7 },
  { id: 'kochschinken', name: 'Kochschinken', kcal: 106, protein: 18, carbs: 1, fat: 3 },
  { id: 'salami', name: 'Salami', kcal: 425, protein: 22, carbs: 1, fat: 38 },
  { id: 'lachsschinken', name: 'Lachsschinken', kcal: 125, protein: 20, carbs: 0.5, fat: 4.5 },

  // Hülsenfrüchte / pflanzliches Protein
  { id: 'linsen_gekocht', name: 'Linsen (gekocht)', kcal: 116, protein: 9, carbs: 20, fat: 0.4 },
  { id: 'kichererbsen_gekocht', name: 'Kichererbsen (gekocht)', kcal: 164, protein: 8.9, carbs: 27, fat: 2.6 },
  { id: 'kidneybohnen_gekocht', name: 'Kidneybohnen (gekocht)', kcal: 127, protein: 8.7, carbs: 22, fat: 0.5 },
  { id: 'tofu', name: 'Tofu', kcal: 121, protein: 13, carbs: 2, fat: 7 },
  { id: 'edamame', name: 'Edamame', kcal: 122, protein: 11, carbs: 9, fat: 5 },
  { id: 'erbsen', name: 'Erbsen', kcal: 81, protein: 5.4, carbs: 14, fat: 0.4 },
  { id: 'hummus', name: 'Hummus', kcal: 166, protein: 7.9, carbs: 14, fat: 9.6 },

  // Nüsse, Samen, Fette
  { id: 'mandeln', name: 'Mandeln', kcal: 579, protein: 21, carbs: 22, fat: 50 },
  { id: 'walnuesse', name: 'Walnüsse', kcal: 654, protein: 15, carbs: 14, fat: 65 },
  { id: 'erdnuesse', name: 'Erdnüsse', kcal: 567, protein: 26, carbs: 16, fat: 49 },
  { id: 'erdnussbutter', name: 'Erdnussbutter', kcal: 588, protein: 25, carbs: 20, fat: 50 },
  { id: 'cashewkerne', name: 'Cashewkerne', kcal: 553, protein: 18, carbs: 30, fat: 44 },
  { id: 'chiasamen', name: 'Chiasamen', kcal: 486, protein: 17, carbs: 42, fat: 31 },
  { id: 'leinsamen', name: 'Leinsamen', kcal: 534, protein: 18, carbs: 29, fat: 42 },
  { id: 'olivenoel', name: 'Olivenöl', kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { id: 'rapsoel', name: 'Rapsöl', kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { id: 'kokosoel', name: 'Kokosöl', kcal: 862, protein: 0, carbs: 0, fat: 100 },
  { id: 'sonnenblumenkerne', name: 'Sonnenblumenkerne', kcal: 584, protein: 21, carbs: 20, fat: 51 },

  // Obst
  { id: 'banane', name: 'Banane', kcal: 89, protein: 1.1, carbs: 23, fat: 0.3 },
  { id: 'apfel', name: 'Apfel', kcal: 52, protein: 0.3, carbs: 14, fat: 0.2 },
  { id: 'birne', name: 'Birne', kcal: 57, protein: 0.4, carbs: 15, fat: 0.1 },
  { id: 'orange', name: 'Orange', kcal: 47, protein: 0.9, carbs: 12, fat: 0.1 },
  { id: 'erdbeeren', name: 'Erdbeeren', kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3 },
  { id: 'heidelbeeren', name: 'Heidelbeeren', kcal: 57, protein: 0.7, carbs: 14, fat: 0.3 },
  { id: 'himbeeren', name: 'Himbeeren', kcal: 52, protein: 1.2, carbs: 12, fat: 0.7 },
  { id: 'weintrauben', name: 'Weintrauben', kcal: 69, protein: 0.6, carbs: 18, fat: 0.2 },
  { id: 'ananas', name: 'Ananas', kcal: 50, protein: 0.5, carbs: 13, fat: 0.1 },
  { id: 'mango', name: 'Mango', kcal: 60, protein: 0.8, carbs: 15, fat: 0.4 },
  { id: 'kiwi', name: 'Kiwi', kcal: 61, protein: 1.1, carbs: 15, fat: 0.5 },
  { id: 'wassermelone', name: 'Wassermelone', kcal: 30, protein: 0.6, carbs: 8, fat: 0.2 },
  { id: 'zitrone', name: 'Zitrone', kcal: 29, protein: 1.1, carbs: 9, fat: 0.3 },
  { id: 'avocado', name: 'Avocado', kcal: 160, protein: 2, carbs: 8.5, fat: 15 },
  { id: 'pfirsich', name: 'Pfirsich', kcal: 39, protein: 0.9, carbs: 10, fat: 0.3 },
  { id: 'datteln', name: 'Datteln (getrocknet)', kcal: 277, protein: 2, carbs: 75, fat: 0.4 },
  { id: 'rosinen', name: 'Rosinen', kcal: 299, protein: 3.1, carbs: 79, fat: 0.5 },

  // Gemüse
  { id: 'brokkoli', name: 'Brokkoli', kcal: 34, protein: 2.8, carbs: 7, fat: 0.4 },
  { id: 'blumenkohl', name: 'Blumenkohl', kcal: 25, protein: 1.9, carbs: 5, fat: 0.3 },
  { id: 'spinat', name: 'Spinat', kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { id: 'gruenkohl', name: 'Grünkohl', kcal: 49, protein: 4.3, carbs: 9, fat: 0.9 },
  { id: 'tomate', name: 'Tomate', kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { id: 'gurke', name: 'Gurke', kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
  { id: 'paprika', name: 'Paprika', kcal: 31, protein: 1, carbs: 6, fat: 0.3 },
  { id: 'karotte', name: 'Karotte', kcal: 41, protein: 0.9, carbs: 10, fat: 0.2 },
  { id: 'zucchini', name: 'Zucchini', kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  { id: 'aubergine', name: 'Aubergine', kcal: 25, protein: 1, carbs: 6, fat: 0.2 },
  { id: 'zwiebel', name: 'Zwiebel', kcal: 40, protein: 1.1, carbs: 9, fat: 0.1 },
  { id: 'knoblauch', name: 'Knoblauch', kcal: 149, protein: 6.4, carbs: 33, fat: 0.5 },
  { id: 'champignons', name: 'Champignons', kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  { id: 'rote_bete', name: 'Rote Bete', kcal: 43, protein: 1.6, carbs: 10, fat: 0.2 },
  { id: 'feldsalat', name: 'Feldsalat', kcal: 20, protein: 2, carbs: 1.6, fat: 0.4 },
  { id: 'rucola', name: 'Rucola', kcal: 25, protein: 2.6, carbs: 2, fat: 0.7 },
  { id: 'eisbergsalat', name: 'Eisbergsalat', kcal: 14, protein: 0.9, carbs: 2.1, fat: 0.2 },
  { id: 'suessmais', name: 'Süßmais', kcal: 86, protein: 3.2, carbs: 19, fat: 1.2 },

  // Sonstiges, Snacks, Getränke
  { id: 'honig', name: 'Honig', kcal: 304, protein: 0.3, carbs: 82, fat: 0 },
  { id: 'ahornsirup', name: 'Ahornsirup', kcal: 260, protein: 0, carbs: 67, fat: 0.2 },
  { id: 'zucker', name: 'Zucker', kcal: 400, protein: 0, carbs: 100, fat: 0 },
  { id: 'schokolade_70', name: 'Dunkle Schokolade (70%)', kcal: 598, protein: 7.8, carbs: 45, fat: 42 },
  { id: 'vollmilchschokolade', name: 'Vollmilchschokolade', kcal: 534, protein: 7.6, carbs: 57, fat: 30 },
  { id: 'proteinpulver', name: 'Proteinpulver (Whey)', kcal: 380, protein: 75, carbs: 8, fat: 6 },
  { id: 'haferdrink', name: 'Haferdrink', kcal: 47, protein: 1, carbs: 6.5, fat: 1.5 },
  { id: 'mandeldrink', name: 'Mandeldrink', kcal: 24, protein: 0.4, carbs: 2.5, fat: 1.1 },
  { id: 'sojamilch', name: 'Sojamilch', kcal: 33, protein: 3.3, carbs: 1.5, fat: 1.8 },
  { id: 'apfelsaft', name: 'Apfelsaft', kcal: 46, protein: 0.1, carbs: 11, fat: 0.1 },
  { id: 'orangensaft', name: 'Orangensaft', kcal: 45, protein: 0.7, carbs: 10, fat: 0.2 },
  { id: 'cola', name: 'Cola', kcal: 42, protein: 0, carbs: 10.6, fat: 0 },
  { id: 'bier', name: 'Bier', kcal: 43, protein: 0.5, carbs: 3.5, fat: 0 },
  { id: 'rotwein', name: 'Rotwein', kcal: 85, protein: 0.1, carbs: 2.6, fat: 0 },
  { id: 'pommes', name: 'Pommes frites', kcal: 312, protein: 3.4, carbs: 41, fat: 15 },
  { id: 'pizza_margherita', name: 'Pizza Margherita', kcal: 266, protein: 11, carbs: 33, fat: 10 },
  { id: 'doener', name: 'Döner Kebab', kcal: 220, protein: 15, carbs: 18, fat: 10 },
  { id: 'currywurst', name: 'Currywurst', kcal: 250, protein: 11, carbs: 10, fat: 18 },
  { id: 'nutella', name: 'Nutella', kcal: 539, protein: 6.3, carbs: 57, fat: 31 },
  { id: 'ketchup', name: 'Ketchup', kcal: 100, protein: 1.2, carbs: 24, fat: 0.2 },
  { id: 'senf', name: 'Senf', kcal: 76, protein: 4.4, carbs: 7.6, fat: 3.9 },
  { id: 'sojasauce', name: 'Sojasauce', kcal: 60, protein: 6, carbs: 6, fat: 0 },
  { id: 'essig', name: 'Essig', kcal: 21, protein: 0, carbs: 0.4, fat: 0 },
  { id: 'vollkorn_wrap', name: 'Vollkorn-Tortilla-Wrap', kcal: 275, protein: 9, carbs: 46, fat: 6 },
  { id: 'kokosmilch', name: 'Kokosmilch (Dose)', kcal: 197, protein: 2, carbs: 3, fat: 20 },
  { id: 'gruene_bohnen', name: 'Grüne Bohnen', kcal: 31, protein: 1.8, carbs: 7, fat: 0.2 },
];

/* Übungen: Home-Training ohne Geräte (Körpergewicht + optional Kurzhanteln/Band) */
const EXERCISES = [
  // Brust
  { id: 'liegestuetze', name: 'Liegestütze', group: 'Brust', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Hände schulterbreit auf dem Boden, Körper bildet eine gerade Linie von Kopf bis Ferse. Brust kontrolliert Richtung Boden senken, dann kraftvoll nach oben drücken.' },
  { id: 'knie_liegestuetze', name: 'Knie-Liegestütze', group: 'Brust', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Wie Liegestütze, aber auf den Knien statt auf den Zehen abgestützt. Reduziert das Gewicht und ist ideal für den Einstieg.' },
  { id: 'diamant_liegestuetze', name: 'Diamant-Liegestütze', group: 'Brust', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Hände bilden unter der Brust eine Raute (Daumen und Zeigefinger berühren sich). Betont besonders Trizeps und inneren Brustmuskel.' },
  { id: 'schraege_liegestuetze', name: 'Schräge Liegestütze (Beine erhöht)', group: 'Brust', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Füße auf einer erhöhten Fläche wie einer Stufe oder einem Stuhl ablegen. Verlagert den Fokus auf die obere Brust.' },
  { id: 'enge_liegestuetze', name: 'Enge Liegestütze', group: 'Brust', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Hände enger als schulterbreit positionieren, Ellbogen eng am Körper führen. Fordert Trizeps und Brust gleichermaßen.' },
  { id: 'plyo_liegestuetze', name: 'Liegestütze mit Klatschen', group: 'Brust', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Explosiv aus der Liegestütz-Position abdrücken, in der Luft in die Hände klatschen und kontrolliert landen. Baut Kraft und Power auf.' },
  { id: 'liegestuetze_erhoeht', name: 'Erhöhte Liegestütze (Füße erhöht)', group: 'Brust', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Füße auf einer erhöhten Fläche wie einer Bank ablegen und die Liegestütze ausführen. Erhöht durch die Gewichtsverlagerung die Intensität deutlich.' },
  { id: 'archer_liegestuetze', name: 'Archer-Liegestütze', group: 'Brust', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Breiter Stand der Hände, Gewicht beim Absenken einseitig auf einen Arm verlagern während der andere Arm gestreckt bleibt. Sehr anspruchsvolle einseitige Variante.' },
  { id: 'brustpresse_kurzhantel', name: 'Brustpresse mit Kurzhanteln', group: 'Brust', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Rückenlage, Kurzhanteln über der Brust nach oben drücken, Ellbogen kontrolliert absenken. Gleichmäßige, ruhige Bewegung.' },
  { id: 'fliegende_kurzhantel', name: 'Fliegende mit Kurzhanteln', group: 'Brust', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Rückenlage, Arme mit leicht gebeugten Ellbogen seitlich absenken und wieder über der Brust zusammenführen. Dehnt und trainiert die Brustmuskulatur.' },

  // Rücken
  { id: 'superman', name: 'Superman', group: 'Rücken', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Bauchlage, Arme und Beine gleichzeitig vom Boden abheben und kurz halten. Stärkt die untere Rückenmuskulatur.' },
  { id: 'rueckenstrecker', name: 'Rückenstrecker (Boden)', group: 'Rücken', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Bauchlage, Hände hinter dem Kopf, Oberkörper langsam anheben und wieder absenken. Kontrolliert ausführen, kein Schwung.' },
  { id: 'reverse_snow_angels', name: 'Reverse Snow Angels', group: 'Rücken', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Bauchlage, Arme wie beim Schneeengel von den Seiten über den Kopf führen und zurück. Aktiviert die obere Rückenmuskulatur.' },
  { id: 'rudern_einarmig', name: 'Kurzhantel Rudern einarmig', group: 'Rücken', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Eine Hand und ein Knie auf einer Bank abstützen, Kurzhantel mit der anderen Hand zur Hüfte ziehen. Rücken gerade halten.' },
  { id: 'band_rudern', name: 'Widerstandsband Rudern', group: 'Rücken', level: 'Mittel', equipment: 'Widerstandsband',
    desc: 'Band um einen festen Punkt spannen, im Sitzen oder Stehen zur Körpermitte ziehen und Schulterblätter zusammenziehen.' },
  { id: 'klimmzuege', name: 'Klimmzüge', group: 'Rücken', level: 'Fortgeschritten', equipment: 'Klimmzugstange',
    desc: 'An einer Stange im Obergriff hängen, Körper hochziehen bis das Kinn über der Stange ist, kontrolliert absenken.' },
  { id: 'good_mornings', name: 'Good Mornings mit Kurzhanteln', group: 'Rücken', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Kurzhantel auf den Schultern, mit leicht gebeugten Knien den Oberkörper nach vorne beugen und wieder aufrichten. Rücken bleibt gerade.' },
  { id: 'band_pull_apart', name: 'Band Pull-Apart', group: 'Rücken', level: 'Anfänger', equipment: 'Widerstandsband',
    desc: 'Band mit ausgestreckten Armen vor der Brust halten und auseinanderziehen, bis es die Brust berührt. Schulterblätter aktiv zusammenziehen.' },

  // Beine
  { id: 'kniebeugen', name: 'Kniebeugen', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Füße schulterbreit, Hüfte nach hinten unten absenken als würde man sich auf einen Stuhl setzen, Knie bleiben über den Füßen.' },
  { id: 'ausfallschritte', name: 'Ausfallschritte', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Großer Schritt nach vorne, hinteres Knie Richtung Boden senken, beide Knie etwa 90 Grad. Zurück zur Ausgangsposition und Seite wechseln.' },
  { id: 'bulgarian_split_squat', name: 'Bulgarian Split Squats', group: 'Beine', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Hinterer Fuß erhöht auf einer Bank abgelegt, mit dem vorderen Bein in die Knie gehen. Fordert Kraft und Balance intensiv.' },
  { id: 'wall_sit', name: 'Wall Sit', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Rücken an eine Wand lehnen und in eine sitzende Position gehen, Oberschenkel parallel zum Boden. Position so lange wie möglich halten.' },
  { id: 'sumo_kniebeuge', name: 'Sumo-Kniebeugen', group: 'Beine', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Breiter Stand, Zehen leicht nach außen gedreht, tief in die Hocke gehen. Betont besonders die Innenschenkel und den Po.' },
  { id: 'jump_squats', name: 'Jump Squats', group: 'Beine', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Aus der Kniebeuge explosiv nach oben springen, weich landen und direkt in die nächste Wiederholung übergehen.' },
  { id: 'glute_bridge', name: 'Glute Bridge', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Rückenlage, Füße aufgestellt, Hüfte nach oben drücken bis der Körper eine gerade Linie bildet, oben kurz halten.' },
  { id: 'wadenheben', name: 'Wadenheben', group: 'Beine', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Im Stehen auf die Zehenspitzen heben und langsam wieder absenken. Für mehr Intensität auf einer Stufenkante ausführen.' },
  { id: 'kurzhantel_kniebeuge', name: 'Kurzhantel Kniebeuge', group: 'Beine', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Kurzhanteln seitlich am Körper halten und eine klassische Kniebeuge ausführen. Erhöht die Belastung gegenüber der Bodyweight-Variante.' },
  { id: 'step_ups', name: 'Step-Ups', group: 'Beine', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Auf eine stabile erhöhte Fläche wie eine Treppenstufe steigen, oben durchstrecken und kontrolliert zurück nach unten.' },

  // Schultern
  { id: 'pike_pushups', name: 'Pike Push-Ups', group: 'Schultern', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Hüfte hoch in eine umgekehrte V-Position bringen, Kopf Richtung Boden absenken und wieder hochdrücken. Betont die vordere Schulter.' },
  { id: 'schulterdruecken', name: 'Schulterdrücken mit Kurzhanteln', group: 'Schultern', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Im Stehen oder Sitzen Kurzhanteln von Schulterhöhe gerade nach oben drücken, ohne den unteren Rücken durchzudrücken.' },
  { id: 'seitheben', name: 'Seitheben mit Kurzhanteln', group: 'Schultern', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Kurzhanteln seitlich am Körper, Arme mit leicht gebeugten Ellbogen bis Schulterhöhe seitlich anheben, kontrolliert absenken.' },
  { id: 'frontheben', name: 'Frontheben mit Kurzhanteln', group: 'Schultern', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Kurzhanteln vor dem Körper, Arme nacheinander oder gemeinsam bis Schulterhöhe nach vorne anheben, langsam zurückführen.' },
  { id: 'arm_circles', name: 'Arm Circles', group: 'Schultern', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Arme seitlich ausstrecken und kleine, kontrollierte Kreise in beide Richtungen ausführen. Gutes Aufwärm- und Aktivierungsmittel.' },
  { id: 'handstand_pushup', name: 'Handstand Push-Up (Wand)', group: 'Schultern', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Im Handstand an der Wand die Arme beugen bis der Kopf sich dem Boden nähert und wieder hochdrücken. Nur mit guter Grundkraft ausführen.' },

  // Arme
  { id: 'bizeps_curls', name: 'Bizeps Curls mit Kurzhanteln', group: 'Arme', level: 'Anfänger', equipment: 'Kurzhanteln',
    desc: 'Oberarme fixiert am Körper, Kurzhanteln durch Beugen der Ellbogen zu den Schultern führen, langsam wieder absenken.' },
  { id: 'trizeps_dips', name: 'Trizeps Dips (Stuhl)', group: 'Arme', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Hände auf die Kante eines Stuhls oder einer Bank stützen, Körper absenken bis die Ellbogen ca. 90 Grad erreichen, wieder hochdrücken.' },
  { id: 'trizeps_kickback', name: 'Trizeps Kickback mit Kurzhantel', group: 'Arme', level: 'Mittel', equipment: 'Kurzhanteln',
    desc: 'Oberkörper leicht vorgebeugt, Oberarm parallel zum Boden, Unterarm nach hinten strecken bis der Arm ganz durchgestreckt ist.' },
  { id: 'hammer_curls', name: 'Hammer Curls', group: 'Arme', level: 'Anfänger', equipment: 'Kurzhanteln',
    desc: 'Kurzhanteln im neutralen Griff (Daumen zeigt nach oben) zu den Schultern curlen. Beansprucht zusätzlich den Unterarm.' },
  { id: 'unterarmrotation', name: 'Unterarmrotation mit Kurzhantel', group: 'Arme', level: 'Anfänger', equipment: 'Kurzhanteln',
    desc: 'Unterarm auf einem Oberschenkel abstützen, Handgelenk mit leichter Kurzhantel kontrolliert drehen. Stärkt Unterarm und Griffkraft.' },

  // Core
  { id: 'plank', name: 'Plank (Unterarmstütz)', group: 'Core', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Unterarme und Zehen am Boden, Körper bildet eine gerade Linie. Bauch und Gesäß aktiv anspannen, Position halten.' },
  { id: 'seitplank', name: 'Seitplank', group: 'Core', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Seitliche Stützposition auf einem Unterarm, Körper bildet eine gerade Linie von Kopf bis Fuß. Hüfte nicht absinken lassen.' },
  { id: 'crunches', name: 'Crunches', group: 'Core', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Rückenlage, Knie angewinkelt, Oberkörper kontrolliert Richtung Knie anheben und wieder absenken, ohne den Nacken zu belasten.' },
  { id: 'bicycle_crunches', name: 'Bicycle Crunches', group: 'Core', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Rückenlage, Ellbogen abwechselnd zum gegenüberliegenden Knie führen, während die Beine eine Radfahrbewegung ausführen.' },
  { id: 'mountain_climbers', name: 'Mountain Climbers', group: 'Core', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Aus der Liegestützposition die Knie abwechselnd schnell Richtung Brust ziehen. Trainiert Core und Herz-Kreislauf-System.' },
  { id: 'russian_twists', name: 'Russian Twists', group: 'Core', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Sitzposition mit leicht angehobenen Füßen, Oberkörper von einer Seite zur anderen drehen. Für mehr Intensität ein Gewicht mitführen.' },
  { id: 'beinheben', name: 'Beinheben', group: 'Core', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Rückenlage, gestreckte Beine kontrolliert anheben bis 90 Grad und langsam wieder absenken, unterer Rücken bleibt am Boden.' },
  { id: 'hollow_body_hold', name: 'Hollow Body Hold', group: 'Core', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Rückenlage, Arme und Beine gestreckt leicht vom Boden abheben, unterer Rücken bleibt gepresst. Position möglichst lange halten.' },
  { id: 'plank_updown', name: 'Plank Up-Down', group: 'Core', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'Aus dem Unterarmstütz abwechselnd in den hohen Stütz auf die Hände hochdrücken und zurück, Hüfte bleibt dabei stabil.' },

  // Cardio
  { id: 'jumping_jacks', name: 'Jumping Jacks', group: 'Cardio', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Aus dem Stand gleichzeitig mit Armen und Beinen nach außen springen, dann zurück in die Ausgangsposition. Klassisches Cardio-Warm-up.' },
  { id: 'burpees', name: 'Burpees', group: 'Cardio', level: 'Fortgeschritten', equipment: 'Körpergewicht',
    desc: 'In die Hocke gehen, in die Liegestützposition springen, eine Liegestütz ausführen, zurückspringen und explosiv nach oben springen.' },
  { id: 'high_knees', name: 'High Knees', group: 'Cardio', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Auf der Stelle laufen und die Knie dabei so hoch wie möglich zur Brust ziehen. Zügiges Tempo für maximale Herzfrequenz.' },
  { id: 'seilspringen', name: 'Seilspringen', group: 'Cardio', level: 'Mittel', equipment: 'Springseil',
    desc: 'Gleichmäßiges Springen über das Seil mit lockeren Handgelenken. Effektives Ganzkörper-Cardio-Training.' },
  { id: 'skaters', name: 'Skaters', group: 'Cardio', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Seitliche Sprünge von einem Bein auf das andere, ähnlich einer Schlittschuh-Bewegung. Trainiert Beine und Koordination.' },
  { id: 'fast_mountain_climbers', name: 'Bergsteiger schnell', group: 'Cardio', level: 'Mittel', equipment: 'Körpergewicht',
    desc: 'Mountain Climbers in schnellem, durchgehendem Tempo für einen erhöhten Cardio-Reiz statt reiner Core-Betonung.' },
  { id: 'shadow_boxing', name: 'Shadow Boxing', group: 'Cardio', level: 'Anfänger', equipment: 'Körpergewicht',
    desc: 'Lockeres Boxen gegen die Luft mit fließenden Schritten. Gelenkschonendes Cardio-Training, das sich beliebig steigern lässt.' },
];

const MUSCLE_GROUPS = ['Brust', 'Rücken', 'Beine', 'Schultern', 'Arme', 'Core', 'Cardio'];

/* Fertige Trainingspläne */
const WORKOUT_PLANS = [
  {
    id: 'starter',
    name: 'STARTER',
    subtitle: 'Ganzkörper für Einsteiger',
    level: 'Anfänger',
    daysPerWeek: 3,
    days: [
      { day: 'Tag 1', label: 'Ganzkörper A', exercises: [
        { exerciseId: 'kniebeugen', sets: 3, reps: '12' },
        { exerciseId: 'knie_liegestuetze', sets: 3, reps: '10' },
        { exerciseId: 'glute_bridge', sets: 3, reps: '15' },
        { exerciseId: 'band_rudern', sets: 3, reps: '12' },
        { exerciseId: 'plank', sets: 3, reps: '30s' },
      ]},
      { day: 'Tag 2', label: 'Ganzkörper B', exercises: [
        { exerciseId: 'ausfallschritte', sets: 3, reps: '10' },
        { exerciseId: 'superman', sets: 3, reps: '15' },
        { exerciseId: 'wall_sit', sets: 3, reps: '30s' },
        { exerciseId: 'band_pull_apart', sets: 3, reps: '15' },
        { exerciseId: 'crunches', sets: 3, reps: '15' },
      ]},
      { day: 'Tag 3', label: 'Ganzkörper C', exercises: [
        { exerciseId: 'sumo_kniebeuge', sets: 3, reps: '12' },
        { exerciseId: 'knie_liegestuetze', sets: 3, reps: '12' },
        { exerciseId: 'rueckenstrecker', sets: 3, reps: '12' },
        { exerciseId: 'wadenheben', sets: 3, reps: '20' },
        { exerciseId: 'seitplank', sets: 3, reps: '20s' },
      ]},
    ],
  },
  {
    id: 'split',
    name: 'SPLIT',
    subtitle: 'Ober-/Unterkörper, 4x pro Woche',
    level: 'Mittel',
    daysPerWeek: 4,
    days: [
      { day: 'Tag 1', label: 'Oberkörper A', exercises: [
        { exerciseId: 'liegestuetze', sets: 4, reps: '10-12' },
        { exerciseId: 'rudern_einarmig', sets: 4, reps: '12' },
        { exerciseId: 'schulterdruecken', sets: 3, reps: '12' },
        { exerciseId: 'bizeps_curls', sets: 3, reps: '12' },
        { exerciseId: 'trizeps_dips', sets: 3, reps: '12' },
      ]},
      { day: 'Tag 2', label: 'Unterkörper A', exercises: [
        { exerciseId: 'kurzhantel_kniebeuge', sets: 4, reps: '10-12' },
        { exerciseId: 'ausfallschritte', sets: 3, reps: '12' },
        { exerciseId: 'glute_bridge', sets: 3, reps: '15' },
        { exerciseId: 'wadenheben', sets: 4, reps: '20' },
        { exerciseId: 'plank', sets: 3, reps: '45s' },
      ]},
      { day: 'Tag 3', label: 'Oberkörper B', exercises: [
        { exerciseId: 'schraege_liegestuetze', sets: 4, reps: '10-12' },
        { exerciseId: 'band_rudern', sets: 4, reps: '12' },
        { exerciseId: 'seitheben', sets: 3, reps: '15' },
        { exerciseId: 'hammer_curls', sets: 3, reps: '12' },
        { exerciseId: 'trizeps_kickback', sets: 3, reps: '12' },
      ]},
      { day: 'Tag 4', label: 'Unterkörper B', exercises: [
        { exerciseId: 'bulgarian_split_squat', sets: 3, reps: '10' },
        { exerciseId: 'sumo_kniebeuge', sets: 4, reps: '12' },
        { exerciseId: 'step_ups', sets: 3, reps: '12' },
        { exerciseId: 'russian_twists', sets: 3, reps: '20' },
        { exerciseId: 'seitplank', sets: 3, reps: '30s' },
      ]},
    ],
  },
  {
    id: 'hiit_home',
    name: 'HIIT HOME',
    subtitle: 'Cardio & Core, 20 Minuten',
    level: 'Mittel',
    daysPerWeek: 3,
    days: [
      { day: 'Tag 1', label: 'HIIT A', type: 'intervall', exercises: [],
        intervall: { arbeitszeit: 40, pausezeit: 20, runden: 8, vorbereitungszeit: 10,
          uebungen: ['jumping_jacks', 'mountain_climbers', 'high_knees', 'plank'] } },
      { day: 'Tag 2', label: 'HIIT B', type: 'intervall', exercises: [],
        intervall: { arbeitszeit: 40, pausezeit: 20, runden: 8, vorbereitungszeit: 10,
          uebungen: ['burpees', 'skaters', 'bicycle_crunches', 'plank_updown'] } },
      { day: 'Tag 3', label: 'HIIT C', type: 'intervall', exercises: [],
        intervall: { arbeitszeit: 40, pausezeit: 20, runden: 8, vorbereitungszeit: 10,
          uebungen: ['fast_mountain_climbers', 'jump_squats', 'russian_twists', 'hollow_body_hold'] } },
    ],
  },
  {
    id: 'ppl',
    name: 'PUSH PULL LEGS',
    subtitle: 'Fortgeschritten, 6x pro Woche',
    level: 'Fortgeschritten',
    daysPerWeek: 6,
    days: [
      { day: 'Tag 1', label: 'Push A', exercises: [
        { exerciseId: 'liegestuetze', sets: 4, reps: '10-15' },
        { exerciseId: 'diamant_liegestuetze', sets: 3, reps: '10' },
        { exerciseId: 'schulterdruecken', sets: 4, reps: '10-12' },
        { exerciseId: 'seitheben', sets: 3, reps: '15' },
        { exerciseId: 'trizeps_dips', sets: 3, reps: '12-15' },
      ]},
      { day: 'Tag 2', label: 'Pull A', exercises: [
        { exerciseId: 'klimmzuege', sets: 4, reps: '6-10' },
        { exerciseId: 'rudern_einarmig', sets: 4, reps: '10-12' },
        { exerciseId: 'good_mornings', sets: 3, reps: '12' },
        { exerciseId: 'bizeps_curls', sets: 3, reps: '12' },
        { exerciseId: 'hammer_curls', sets: 3, reps: '12' },
      ]},
      { day: 'Tag 3', label: 'Legs A', exercises: [
        { exerciseId: 'kurzhantel_kniebeuge', sets: 4, reps: '10-12' },
        { exerciseId: 'bulgarian_split_squat', sets: 3, reps: '10' },
        { exerciseId: 'glute_bridge', sets: 4, reps: '15' },
        { exerciseId: 'wadenheben', sets: 4, reps: '20' },
        { exerciseId: 'plank', sets: 3, reps: '45s' },
      ]},
      { day: 'Tag 4', label: 'Push B', exercises: [
        { exerciseId: 'schraege_liegestuetze', sets: 4, reps: '10-15' },
        { exerciseId: 'pike_pushups', sets: 3, reps: '8-10' },
        { exerciseId: 'fliegende_kurzhantel', sets: 3, reps: '12' },
        { exerciseId: 'frontheben', sets: 3, reps: '15' },
        { exerciseId: 'trizeps_kickback', sets: 3, reps: '12' },
      ]},
      { day: 'Tag 5', label: 'Pull B', exercises: [
        { exerciseId: 'band_rudern', sets: 4, reps: '12-15' },
        { exerciseId: 'reverse_snow_angels', sets: 3, reps: '15' },
        { exerciseId: 'band_pull_apart', sets: 3, reps: '20' },
        { exerciseId: 'unterarmrotation', sets: 3, reps: '15' },
        { exerciseId: 'plank_updown', sets: 3, reps: '30s' },
      ]},
      { day: 'Tag 6', label: 'Legs B', exercises: [
        { exerciseId: 'sumo_kniebeuge', sets: 4, reps: '12-15' },
        { exerciseId: 'ausfallschritte', sets: 3, reps: '12' },
        { exerciseId: 'step_ups', sets: 3, reps: '12' },
        { exerciseId: 'jump_squats', sets: 3, reps: '15' },
        { exerciseId: 'russian_twists', sets: 3, reps: '20' },
      ]},
    ],
  },
];

/* Progressionsketten für Körpergewichtsübungen: aktuelle Übung -> nächste Stufe.
   Vorschlag greift, wenn 3 Sätze mit je 15+ Wdh erreicht wurden. */
const BODYWEIGHT_PROGRESSIONS = {
  knie_liegestuetze: 'liegestuetze',
  liegestuetze: 'liegestuetze_erhoeht',
  liegestuetze_erhoeht: 'archer_liegestuetze',
  kniebeugen: 'ausfallschritte',
  ausfallschritte: 'bulgarian_split_squat',
  bulgarian_split_squat: 'jump_squats',
  plank: 'plank_updown',
  plank_updown: 'hollow_body_hold',
  crunches: 'bicycle_crunches',
  bicycle_crunches: 'beinheben',
};

/* ==========================================================================
   Rezepte — Zutaten referenzieren FOOD_DB per foodId, damit Nährwerte
   automatisch und konsistent aus den Zutaten berechnet werden.
   ========================================================================== */

function ing(foodId, grams, menge, einheit) {
  return { foodId, grams, menge: menge !== undefined ? menge : grams, einheit: einheit || 'g' };
}

const RECIPES_RAW = [
  // ---------- FRÜHSTÜCK (10) ----------
  { id: 'rec_porridge_skyr', name: 'Protein-Porridge mit Skyr', kategorie: 'Frühstück', zubereitungszeit: 8, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('haferflocken', 50), ing('skyr', 150), ing('banane', 60), ing('heidelbeeren', 50)],
    zubereitung: ['Haferflocken mit etwas Wasser oder Milch kurz aufkochen und quellen lassen.', 'Skyr unterrühren.', 'Banane in Scheiben schneiden und mit den Heidelbeeren darauf verteilen.'] },
  { id: 'rec_ruehrei_vollkornbrot', name: 'Rührei auf Vollkornbrot', kategorie: 'Frühstück', zubereitungszeit: 10, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('ei', 150, 3, 'Stück'), ing('brot_vollkorn', 60), ing('butter', 5), ing('tomate', 50)],
    zubereitung: ['Eier verquirlen, salzen und pfeffern.', 'Butter in der Pfanne erhitzen und die Eier bei mittlerer Hitze stocken lassen, dabei stetig rühren.', 'Brot toasten und mit dem Rührei und Tomatenscheiben servieren.'] },
  { id: 'rec_overnight_oats', name: 'Overnight Oats mit Beeren', kategorie: 'Frühstück', zubereitungszeit: 5, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('haferflocken', 50), ing('milch_15', 150), ing('chiasamen', 10), ing('himbeeren', 60), ing('honig', 10)],
    zubereitung: ['Haferflocken, Milch, Chiasamen und Honig in einem Glas vermischen.', 'Über Nacht abgedeckt im Kühlschrank quellen lassen.', 'Am Morgen mit den Himbeeren toppen.'] },
  { id: 'rec_quark_beeren_nuesse', name: 'Quark mit Beeren und Nüssen', kategorie: 'Frühstück', zubereitungszeit: 5, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('magerquark', 200), ing('erdbeeren', 80), ing('walnuesse', 15), ing('honig', 10)],
    zubereitung: ['Magerquark glattrühren und mit Honig verfeinern.', 'Erdbeeren klein schneiden und unterheben.', 'Mit gehackten Walnüssen bestreuen.'] },
  { id: 'rec_protein_pancakes', name: 'Protein-Pancakes', kategorie: 'Frühstück', zubereitungszeit: 15, schwierigkeit: 'mittel', vegetarisch: true, vegan: false,
    zutaten: [ing('haferflocken', 50), ing('ei', 100, 2, 'Stück'), ing('skyr', 50), ing('banane', 60)],
    zubereitung: ['Haferflocken, Eier, Skyr und die halbe Banane im Mixer glatt pürieren.', 'Teig portionsweise in einer beschichteten Pfanne bei mittlerer Hitze von beiden Seiten goldbraun backen.', 'Mit der restlichen Banane in Scheiben servieren.'] },
  { id: 'rec_griech_joghurt_bowl', name: 'Griechischer Joghurt Bowl', kategorie: 'Frühstück', zubereitungszeit: 5, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('griech_joghurt', 200), ing('mandeln', 15), ing('honig', 10), ing('heidelbeeren', 50)],
    zubereitung: ['Joghurt in eine Schale füllen.', 'Mit Mandeln und Heidelbeeren toppen.', 'Mit Honig beträufeln.'] },
  { id: 'rec_toast_avocado_ei', name: 'Vollkorn-Toast mit Avocado und Ei', kategorie: 'Frühstück', zubereitungszeit: 10, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('brot_vollkorn', 60), ing('avocado', 70), ing('ei', 55, 1, 'Stück')],
    zubereitung: ['Brot toasten.', 'Avocado zerdrücken, salzen und pfeffern, auf dem Toast verteilen.', 'Ei pochieren oder als Spiegelei braten und obenauf legen.'] },
  { id: 'rec_skyr_porridge_apfel', name: 'Skyr-Porridge mit Zimt und Apfel', kategorie: 'Frühstück', zubereitungszeit: 8, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('skyr', 150), ing('haferflocken', 40), ing('apfel', 100)],
    zubereitung: ['Haferflocken mit etwas Wasser kurz aufkochen.', 'Skyr und in Würfel geschnittenen Apfel unterrühren.', 'Nach Belieben mit Zimt bestreuen.'] },
  { id: 'rec_ruehrei_huettenkaese_spinat', name: 'Rührei mit Hüttenkäse und Spinat', kategorie: 'Frühstück', zubereitungszeit: 10, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('ei', 100, 2, 'Stück'), ing('huettenkaese', 100), ing('spinat', 50)],
    zubereitung: ['Spinat in einer Pfanne kurz zusammenfallen lassen.', 'Verquirlte Eier dazugeben und stocken lassen.', 'Hüttenkäse unterheben und warm servieren.'] },
  { id: 'rec_banane_hafer_smoothie', name: 'Bananen-Hafer-Smoothie', kategorie: 'Frühstück', zubereitungszeit: 5, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('banane', 120), ing('haferflocken', 30), ing('milch_15', 200), ing('erdnussbutter', 15), ing('proteinpulver', 15)],
    zubereitung: ['Alle Zutaten in einen Mixer geben.', 'Cremig pürieren.', 'Sofort servieren.'] },

  // ---------- MITTAG (12) ----------
  { id: 'rec_haehnchen_reis_bowl', name: 'Hähnchen-Reis-Bowl', kategorie: 'Mittag', zubereitungszeit: 25, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('haehnchenbrust', 150), ing('reis_gekocht', 200), ing('brokkoli', 100), ing('olivenoel', 10)],
    zubereitung: ['Hähnchenbrust würzen und in einer Pfanne mit etwas Öl durchbraten.', 'Brokkoli in Röschen teilen und dämpfen oder kurz kochen.', 'Reis, Hähnchen und Brokkoli in einer Bowl anrichten und mit Olivenöl beträufeln.'] },
  { id: 'rec_linsen_curry', name: 'Linsen-Curry', kategorie: 'Mittag', zubereitungszeit: 25, schwierigkeit: 'mittel', vegetarisch: true, vegan: true,
    zutaten: [ing('linsen_gekocht', 200), ing('kokosoel', 10), ing('tomate', 100), ing('reis_gekocht', 150), ing('zwiebel', 40)],
    zubereitung: ['Zwiebel in Kokosöl glasig dünsten.', 'Tomaten und Currygewürz dazugeben und kurz köcheln.', 'Linsen unterrühren und einige Minuten ziehen lassen.', 'Mit Reis servieren.'] },
  { id: 'rec_putenstreifen_suesskartoffel', name: 'Putenstreifen mit Süßkartoffel', kategorie: 'Mittag', zubereitungszeit: 25, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('putenbrust', 150), ing('suesskartoffel', 200), ing('paprika', 80), ing('olivenoel', 10)],
    zubereitung: ['Süßkartoffel würfeln und im Ofen bei 200°C ca. 20 Minuten rösten.', 'Putenbrust in Streifen schneiden und in Olivenöl anbraten.', 'Paprika kurz mitbraten und alles zusammen servieren.'] },
  { id: 'rec_thunfisch_wrap', name: 'Thunfisch-Wrap', kategorie: 'Mittag', zubereitungszeit: 10, schwierigkeit: 'leicht', vegetarisch: false, vegan: false,
    zutaten: [ing('thunfisch_dose', 100), ing('vollkorn_wrap', 70), ing('joghurt_natur', 30), ing('eisbergsalat', 30), ing('tomate', 40)],
    zubereitung: ['Thunfisch abtropfen lassen und mit Joghurt vermengen.', 'Salat und Tomatenwürfel auf dem Wrap verteilen.', 'Thunfischmischung daraufgeben und den Wrap fest einrollen.'] },
  { id: 'rec_gemuese_omelett', name: 'Gemüse-Omelett', kategorie: 'Mittag', zubereitungszeit: 15, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('ei', 150, 3, 'Stück'), ing('paprika', 50), ing('champignons', 50), ing('zwiebel', 30), ing('feta', 30)],
    zubereitung: ['Gemüse klein schneiden und in einer Pfanne andünsten.', 'Verquirlte Eier darübergießen und bei niedriger Hitze stocken lassen.', 'Feta zerbröckeln, darüberstreuen und die Pfanne zusammenklappen.'] },
  { id: 'rec_quinoa_kichererbsen', name: 'Quinoa-Bowl mit Kichererbsen', kategorie: 'Mittag', zubereitungszeit: 20, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('quinoa_gekocht', 180), ing('kichererbsen_gekocht', 100), ing('gurke', 60), ing('feta', 30), ing('olivenoel', 10)],
    zubereitung: ['Quinoa und Kichererbsen in einer Bowl vermengen.', 'Gurke würfeln und dazugeben.', 'Mit Feta und Olivenöl abschließen.'] },
  { id: 'rec_haehnchen_avocado_salat', name: 'Hähnchen-Salat mit Avocado', kategorie: 'Mittag', zubereitungszeit: 20, schwierigkeit: 'leicht', vegetarisch: false, vegan: false,
    zutaten: [ing('haehnchenbrust', 150), ing('feldsalat', 60), ing('avocado', 60), ing('tomate', 60), ing('olivenoel', 10)],
    zubereitung: ['Hähnchenbrust würzen und braten, dann in Streifen schneiden.', 'Feldsalat, Avocadowürfel und Tomaten in einer Schüssel anrichten.', 'Hähnchen daraufgeben und mit Olivenöl beträufeln.'] },
  { id: 'rec_nudeln_haehnchen_brokkoli', name: 'Nudeln mit Hähnchen und Brokkoli', kategorie: 'Mittag', zubereitungszeit: 25, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('vollkornnudeln_gekocht', 200), ing('haehnchenbrust', 120), ing('brokkoli', 100), ing('parmesan', 15)],
    zubereitung: ['Nudeln nach Packungsanweisung kochen.', 'Hähnchenbrust würfeln und anbraten, Brokkoli mitdünsten.', 'Mit den Nudeln vermengen und Parmesan darüberreiben.'] },
  { id: 'rec_falafel_bowl', name: 'Falafel-Bowl mit Kichererbsen', kategorie: 'Mittag', zubereitungszeit: 25, schwierigkeit: 'mittel', vegetarisch: true, vegan: false,
    zutaten: [ing('kichererbsen_gekocht', 180), ing('reis_gekocht', 150), ing('gurke', 60), ing('joghurt_natur', 50), ing('olivenoel', 5)],
    zubereitung: ['Kichererbsen in einer Pfanne mit etwas Öl knusprig anbraten und würzen.', 'Reis und Gurkenwürfel in eine Bowl geben.', 'Kichererbsen daraufgeben und mit einem Klecks Joghurt servieren.'] },
  { id: 'rec_garnelen_reis_pfanne', name: 'Garnelen-Reis-Pfanne', kategorie: 'Mittag', zubereitungszeit: 20, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('garnelen', 150), ing('reis_gekocht', 180), ing('paprika', 60), ing('zucchini', 60), ing('olivenoel', 10)],
    zubereitung: ['Paprika und Zucchini in Streifen schneiden und in Olivenöl anbraten.', 'Garnelen dazugeben und kurz mitbraten, bis sie rosa sind.', 'Reis unterheben und alles gut vermengen.'] },
  { id: 'rec_putengeschnetzeltes_reis', name: 'Putengeschnetzeltes mit Reis', kategorie: 'Mittag', zubereitungszeit: 20, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('putenbrust', 150), ing('reis_gekocht', 180), ing('champignons', 80), ing('zwiebel', 30)],
    zubereitung: ['Putenbrust in Streifen schneiden und scharf anbraten.', 'Zwiebel und Champignons dazugeben und mitbraten.', 'Mit Reis servieren.'] },
  { id: 'rec_veggie_bowl_linsen', name: 'Veggie-Bowl mit Linsen', kategorie: 'Mittag', zubereitungszeit: 20, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('linsen_gekocht', 180), ing('suesskartoffel', 150), ing('rucola', 30), ing('joghurt_natur', 30)],
    zubereitung: ['Süßkartoffel würfeln und im Ofen rösten, bis sie weich ist.', 'Linsen erwärmen und mit der Süßkartoffel und Rucola in einer Bowl anrichten.', 'Mit einem Klecks Joghurt servieren.'] },

  // ---------- ABEND (12) ----------
  { id: 'rec_lachs_brokkoli', name: 'Lachs mit Brokkoli', kategorie: 'Abend', zubereitungszeit: 20, schwierigkeit: 'leicht', vegetarisch: false, vegan: false,
    zutaten: [ing('lachs', 150), ing('brokkoli', 150), ing('olivenoel', 10)],
    zubereitung: ['Lachs salzen und in einer Pfanne mit Olivenöl von beiden Seiten braten.', 'Brokkoli dämpfen, bis er bissfest ist.', 'Zusammen servieren.'] },
  { id: 'rec_magerquark_fladen', name: 'Magerquark-Fladen', kategorie: 'Abend', zubereitungszeit: 15, schwierigkeit: 'mittel', vegetarisch: true, vegan: false,
    zutaten: [ing('magerquark', 150), ing('ei', 55, 1, 'Stück'), ing('haferflocken', 30)],
    zubereitung: ['Magerquark, Ei und Haferflocken zu einem Teig verrühren.', 'Teig in einer beschichteten Pfanne zu einem Fladen ausbacken.', 'Von beiden Seiten goldbraun braten.'] },
  { id: 'rec_hackfleisch_gemuesepfanne', name: 'Hackfleisch-Gemüsepfanne', kategorie: 'Abend', zubereitungszeit: 25, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('rinderhack', 150), ing('zucchini', 100), ing('paprika', 80), ing('tomate', 80), ing('zwiebel', 40)],
    zubereitung: ['Zwiebel andünsten, Hackfleisch dazugeben und krümelig anbraten.', 'Zucchini und Paprika hinzufügen und mitbraten.', 'Tomaten zum Schluss unterrühren und kurz köcheln lassen.'] },
  { id: 'rec_gefuellte_paprika', name: 'Gefüllte Paprika mit Hackfleisch und Reis', kategorie: 'Abend', zubereitungszeit: 35, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('paprika', 150, 1, 'Stück'), ing('rinderhack', 120), ing('reis_gekocht', 100), ing('gouda', 20)],
    zubereitung: ['Paprika halbieren und entkernen.', 'Hackfleisch anbraten und mit Reis vermengen, würzen.', 'Paprikahälften füllen, mit Käse bestreuen und im Ofen bei 200°C 20 Minuten überbacken.'] },
  { id: 'rec_shakshuka', name: 'Shakshuka', kategorie: 'Abend', zubereitungszeit: 20, schwierigkeit: 'mittel', vegetarisch: true, vegan: false,
    zutaten: [ing('ei', 110, 2, 'Stück'), ing('tomate', 200), ing('paprika', 80), ing('zwiebel', 40), ing('feta', 30)],
    zubereitung: ['Zwiebel und Paprika andünsten, Tomaten dazugeben und zu einer Sauce einkochen.', 'Mit Paprikapulver und Kreuzkümmel würzen.', 'Mulden in die Sauce drücken, Eier hineingeben und stocken lassen.', 'Mit Feta bestreuen.'] },
  { id: 'rec_kabeljau_ofengemuese', name: 'Kabeljau mit Ofengemüse', kategorie: 'Abend', zubereitungszeit: 30, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('kabeljau', 150), ing('zucchini', 100), ing('paprika', 80), ing('olivenoel', 10)],
    zubereitung: ['Zucchini und Paprika mit Olivenöl vermengen und im Ofen bei 200°C 15 Minuten rösten.', 'Kabeljau würzen und dazulegen.', 'Weitere 12-15 Minuten fertig garen.'] },
  { id: 'rec_tofu_gemuesepfanne', name: 'Tofu-Gemüsepfanne', kategorie: 'Abend', zubereitungszeit: 20, schwierigkeit: 'mittel', vegetarisch: true, vegan: true,
    zutaten: [ing('tofu', 150), ing('brokkoli', 100), ing('paprika', 80), ing('sojasauce', 10), ing('reis_gekocht', 100)],
    zubereitung: ['Tofu würfeln und knusprig anbraten.', 'Brokkoli und Paprika dazugeben und mitbraten.', 'Mit Sojasauce ablöschen und mit Reis servieren.'] },
  { id: 'rec_haehnchen_curry_kokos', name: 'Hähnchen-Curry mit Kokosmilch', kategorie: 'Abend', zubereitungszeit: 30, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('haehnchenbrust', 150), ing('kokosmilch', 100), ing('brokkoli', 100), ing('reis_gekocht', 150)],
    zubereitung: ['Hähnchenbrust würfeln und anbraten.', 'Currypaste kurz mitrösten, Kokosmilch angießen.', 'Brokkoli dazugeben und köcheln, bis alles gar ist.', 'Mit Reis servieren.'] },
  { id: 'rec_putenbrust_gruene_bohnen', name: 'Putenbrust mit grünen Bohnen', kategorie: 'Abend', zubereitungszeit: 25, schwierigkeit: 'leicht', vegetarisch: false, vegan: false,
    zutaten: [ing('putenbrust', 150), ing('gruene_bohnen', 150), ing('kartoffeln', 150)],
    zubereitung: ['Kartoffeln schälen, würfeln und kochen.', 'Putenbrust würzen und braten.', 'Grüne Bohnen dämpfen und alles zusammen servieren.'] },
  { id: 'rec_rindergeschnetzeltes_champignons', name: 'Rindergeschnetzeltes mit Champignons', kategorie: 'Abend', zubereitungszeit: 25, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('rinderfilet', 150), ing('champignons', 100), ing('zwiebel', 40), ing('reis_gekocht', 150)],
    zubereitung: ['Rinderfilet in Streifen schneiden und scharf anbraten.', 'Zwiebel und Champignons dazugeben und mitbraten.', 'Mit Reis servieren.'] },
  { id: 'rec_lachs_suesskartoffelpueree', name: 'Gebackener Lachs mit Süßkartoffelpüree', kategorie: 'Abend', zubereitungszeit: 30, schwierigkeit: 'mittel', vegetarisch: false, vegan: false,
    zutaten: [ing('lachs', 150), ing('suesskartoffel', 200), ing('spinat', 60)],
    zubereitung: ['Süßkartoffel weich kochen und zu Püree stampfen.', 'Lachs im Ofen bei 200°C ca. 15 Minuten backen.', 'Spinat kurz andünsten und alles zusammen anrichten.'] },
  { id: 'rec_linsen_bolognese_zucchini', name: 'Linsen-Bolognese mit Zucchininudeln', kategorie: 'Abend', zubereitungszeit: 25, schwierigkeit: 'mittel', vegetarisch: true, vegan: true,
    zutaten: [ing('linsen_gekocht', 200), ing('zucchini', 200), ing('tomate', 100), ing('zwiebel', 30)],
    zubereitung: ['Zucchini mit dem Spiralschneider zu Nudeln verarbeiten.', 'Zwiebel andünsten, Tomaten und Linsen dazugeben und zu einer Sauce einkochen.', 'Zucchininudeln kurz mitschwenken und servieren.'] },

  // ---------- SNACKS (6) ----------
  { id: 'rec_skyr_bowl_beeren', name: 'Skyr-Bowl mit Beeren', kategorie: 'Snacks', zubereitungszeit: 3, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('skyr', 200), ing('heidelbeeren', 60), ing('honig', 5)],
    zubereitung: ['Skyr in eine Schale füllen.', 'Mit Heidelbeeren toppen und mit Honig beträufeln.'] },
  { id: 'rec_reiswaffeln_huettenkaese', name: 'Reiswaffeln mit Hüttenkäse', kategorie: 'Snacks', zubereitungszeit: 3, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('reiswaffeln', 20, 2, 'Stück'), ing('huettenkaese', 100), ing('tomate', 40)],
    zubereitung: ['Hüttenkäse auf den Reiswaffeln verteilen.', 'Mit Tomatenscheiben belegen.'] },
  { id: 'rec_proteinshake_banane', name: 'Proteinshake mit Banane', kategorie: 'Snacks', zubereitungszeit: 3, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('proteinpulver', 30), ing('milch_15', 250), ing('banane', 100)],
    zubereitung: ['Alle Zutaten in den Mixer geben.', 'Cremig pürieren und sofort trinken.'] },
  { id: 'rec_edamame_salz', name: 'Edamame mit Meersalz', kategorie: 'Snacks', zubereitungszeit: 8, schwierigkeit: 'leicht', vegetarisch: true, vegan: true,
    zutaten: [ing('edamame', 150)],
    zubereitung: ['Edamame in kochendem Salzwasser ca. 5 Minuten garen.', 'Abgießen und mit grobem Meersalz bestreuen.'] },
  { id: 'rec_apfel_erdnussbutter', name: 'Apfel mit Erdnussbutter', kategorie: 'Snacks', zubereitungszeit: 2, schwierigkeit: 'leicht', vegetarisch: true, vegan: true,
    zutaten: [ing('apfel', 150), ing('erdnussbutter', 20)],
    zubereitung: ['Apfel in Spalten schneiden.', 'Mit Erdnussbutter servieren oder bestreichen.'] },
  { id: 'rec_huettenkaese_ananas', name: 'Hüttenkäse mit Ananas', kategorie: 'Snacks', zubereitungszeit: 3, schwierigkeit: 'leicht', vegetarisch: true, vegan: false,
    zutaten: [ing('huettenkaese', 150), ing('ananas', 80)],
    zubereitung: ['Hüttenkäse in eine Schale geben.', 'Ananasstücke daraufgeben.'] },
];

function buildRecipe(raw) {
  const zutaten = raw.zutaten.map((z) => {
    const food = FOOD_DB.find((f) => f.id === z.foodId);
    const factor = z.grams / 100;
    return {
      foodId: z.foodId,
      name: food ? food.name : z.foodId,
      menge: z.menge,
      einheit: z.einheit,
      grams: z.grams,
      kcal: Math.round(food.kcal * factor * 10) / 10,
      protein: Math.round(food.protein * factor * 10) / 10,
      kh: Math.round(food.carbs * factor * 10) / 10,
      fett: Math.round(food.fat * factor * 10) / 10,
    };
  });
  const totals = zutaten.reduce(
    (acc, z) => {
      acc.kcal += z.kcal;
      acc.protein += z.protein;
      acc.kh += z.kh;
      acc.fett += z.fett;
      return acc;
    },
    { kcal: 0, protein: 0, kh: 0, fett: 0 }
  );
  const gesamtNaehrwerte = {
    kcal: Math.round(totals.kcal),
    protein: Math.round(totals.protein * 10) / 10,
    kh: Math.round(totals.kh * 10) / 10,
    fett: Math.round(totals.fett * 10) / 10,
  };
  const tags = [];
  if (raw.vegetarisch) tags.push('vegetarisch');
  if (raw.vegan) tags.push('vegan');
  if (gesamtNaehrwerte.protein >= 25) tags.push('proteinreich');
  if (gesamtNaehrwerte.kcal <= 400) tags.push('low-cal');
  if (raw.zubereitungszeit <= 15) tags.push('schnell');

  return {
    id: raw.id,
    name: raw.name,
    kategorie: raw.kategorie,
    zubereitungszeit: raw.zubereitungszeit,
    schwierigkeit: raw.schwierigkeit,
    tags,
    portionen: 1,
    zutaten,
    gesamtNaehrwerte,
    zubereitung: raw.zubereitung,
    custom: false,
  };
}

const RECIPES = RECIPES_RAW.map(buildRecipe);

if (typeof module !== 'undefined') {
  module.exports = { FOOD_DB, EXERCISES, MUSCLE_GROUPS, WORKOUT_PLANS, BODYWEIGHT_PROGRESSIONS, RECIPES, buildRecipe };
}
